import { getBackendUrl } from '@/lib/backend'
import React, { useState, useMemo, useEffect } from 'react'
import { useQuery } from '@tanstack/react-query'
import { useNavigate } from 'react-router-dom'
import { supabase } from '@/lib/supabase'
import {
  FileText, Download, Loader2, ChevronLeft, ChevronRight, Printer,
  ExternalLink, Share2, ChevronDown, ChevronUp, ArrowUpDown, Search,
  CalendarRange, CloudUpload, Mail,
} from 'lucide-react'
import { generateAndDownloadPdf } from '@/lib/pdf-utils'
import { useAccentColors } from '@/lib/accent-colors'


interface ApprovedOffering {
  id: number
  filename: string | null
  offering_date: string | null
  general: number
  cash: number
  sunday_school: number
  building_fund: number
  misc: number
  notes: string | null
  approved_by_email: string | null
  locked_at: string | null
}

type SortKey = 'offering_date' | 'general' | 'cash' | 'sunday_school' | 'building_fund' | 'misc' | 'total'
type SortDir = 'asc' | 'desc'
type ViewMode = 'monthly' | 'yearly' | 'range'

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December']

const COLUMNS: { key: SortKey; label: string }[] = [
  { key: 'offering_date', label: 'Date' },
  { key: 'general', label: 'General' },
  { key: 'cash', label: 'Cash' },
  { key: 'sunday_school', label: 'Sunday School' },
  { key: 'building_fund', label: 'Building Fund' },
  { key: 'misc', label: 'Miscellaneous' },
  { key: 'total', label: 'Total' },
]

const parseOfferingDate = (d: string | null): Date | null => {
  if (!d) return null
  const slashMatch = d.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/)
  if (slashMatch) return new Date(+slashMatch[3], +slashMatch[1] - 1, +slashMatch[2])
  const isoMatch = d.match(/^(\d{4})-(\d{2})-(\d{2})/)
  if (isoMatch) return new Date(+isoMatch[1], +isoMatch[2] - 1, +isoMatch[3])
  return null
}

const formatDate = (d: string | null) => {
  if (!d) return '—'
  if (d.includes('/')) return d
  const [y, m, day] = d.split('-')
  return `${m}/${day}/${y}`
}

const fmt = (n: number) => n > 0 ? `$${n.toFixed(2)}` : '—'
const rowTotal = (o: ApprovedOffering) =>
  (o.general || 0) + (o.cash || 0) + (o.sunday_school || 0) + (o.building_fund || 0) + (o.misc || 0)

// Open HTML in new window (no auto-print — user can Cmd+P when ready)
// Email-safe card using tables instead of flexbox (Gmail/Outlook compatible)
function buildEmailCard(churchName: string, o: ApprovedOffering, accent = '#4f46e5'): string {
  const t = rowTotal(o)
  const row = (label: string, amount: number) =>
    '<tr><td style="padding:8px 20px;font-size:14px;color:#374151;border-bottom:1px solid #f1f5f9">' + label + '</td>' +
    '<td style="padding:8px 20px;font-size:14px;text-align:right;border-bottom:1px solid #f1f5f9;font-weight:500">$' + amount.toFixed(2) + '</td></tr>'

  let rows = ''
  if (o.general > 0) rows += row('General (Checks)', o.general)
  if (o.cash > 0) rows += row('Cash (Denominations)', o.cash)
  if (o.sunday_school > 0) rows += row('Sunday School', o.sunday_school)
  if (o.building_fund > 0) rows += row('Building Fund', o.building_fund)
  if (o.misc > 0) rows += row('Miscellaneous', o.misc)

  return '<div style="max-width:420px;margin:0 auto;font-family:system-ui,-apple-system,sans-serif">' +
    '<table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e5e7eb;border-radius:8px;overflow:hidden">' +
      '<tr><td style="background:' + accent + ';padding:16px 20px">' +
        '<p style="margin:0;font-size:16px;font-weight:600;color:#ffffff">' + churchName + '</p>' +
        '<p style="margin:4px 0 0;font-size:12px;color:rgba(255,255,255,0.8)">Week of ' + formatDate(o.offering_date) + '</p>' +
      '</td></tr>' +
      '<tr><td style="padding:0">' +
        '<table width="100%" cellpadding="0" cellspacing="0">' +
          rows +
          '<tr style="border-top:2px solid ' + accent + '">' +
            '<td style="padding:12px 20px;font-size:16px;font-weight:bold;color:' + accent + '">Total</td>' +
            '<td style="padding:12px 20px;font-size:16px;font-weight:bold;color:' + accent + ';text-align:right">$' + t.toFixed(2) + '</td>' +
          '</tr>' +
        '</table>' +
      '</td></tr>' +
    '</table>' +
    '<p style="margin:12px 0 0;font-size:10px;color:#94a3b8;text-align:center">Generated by OTS on ' + new Date().toLocaleDateString() + '</p>' +
  '</div>'
}

function buildReportTable(offerings: ApprovedOffering[], grandTotal: Record<string, number>, grandTotalSum: number): string {
  const rows = offerings.map(o => `<tr>
    <td class="left">${formatDate(o.offering_date)}</td>
    <td class="right">${fmt(o.general)}</td><td class="right">${fmt(o.cash)}</td>
    <td class="right">${fmt(o.sunday_school)}</td><td class="right">${fmt(o.building_fund)}</td>
    <td class="right">${fmt(o.misc)}</td>
    <td class="right"><strong>$${rowTotal(o).toFixed(2)}</strong></td>
  </tr>`).join('')

  return `<table><thead><tr>
    <th class="left">Date</th><th class="right">General</th><th class="right">Cash</th>
    <th class="right">Sunday School</th><th class="right">Building Fund</th>
    <th class="right">Misc</th><th class="right">Total</th>
  </tr></thead><tbody>${rows}</tbody><tfoot><tr>
    <td class="left"><strong>Total</strong></td>
    <td class="right">$${grandTotal.general.toFixed(2)}</td><td class="right">$${grandTotal.cash.toFixed(2)}</td>
    <td class="right">$${grandTotal.sunday_school.toFixed(2)}</td><td class="right">$${grandTotal.building_fund.toFixed(2)}</td>
    <td class="right">$${grandTotal.misc.toFixed(2)}</td>
    <td class="right"><strong>$${grandTotalSum.toFixed(2)}</strong></td>
  </tr></tfoot></table>`
}

function MonthCalendar({ year, month, offerings, missingSundays, onSelectDate }: {
  year: number
  month: number
  offerings: ApprovedOffering[]
  missingSundays: string[]
  onSelectDate: (offeringId: number | null) => void
}) {
  // Build calendar grid
  const firstDay = new Date(year, month, 1)
  const lastDay = new Date(year, month + 1, 0)
  const startPad = firstDay.getDay() // 0=Sun
  const totalDays = lastDay.getDate()
  const today = new Date()

  // Map offering dates to their data
  const offeringByDate = new Map<string, ApprovedOffering>()
  for (const o of offerings) {
    const d = parseOfferingDate(o.offering_date)
    if (d) offeringByDate.set(d.toDateString(), o)
  }

  const missingSet = new Set(missingSundays.map(s => parseOfferingDate(s)?.toDateString()).filter(Boolean))

  const days: Array<{ day: number; date: Date; isSunday: boolean; offering: ApprovedOffering | null; isMissing: boolean; isToday: boolean; isFuture: boolean }> = []
  for (let d = 1; d <= totalDays; d++) {
    const date = new Date(year, month, d)
    const key = date.toDateString()
    days.push({
      day: d,
      date,
      isSunday: date.getDay() === 0,
      offering: offeringByDate.get(key) || null,
      isMissing: missingSet.has(key),
      isToday: key === today.toDateString(),
      isFuture: date > today,
    })
  }

  return (
    <div className="rounded-xl border border-border bg-card overflow-hidden">
      <div className="grid grid-cols-7 text-center text-[10px] text-muted font-medium border-b border-border bg-card">
        {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(d => (
          <div key={d} className={`py-1.5 ${d === 'Sun' ? 'text-primary font-bold' : ''}`}>{d}</div>
        ))}
      </div>
      <div className="grid grid-cols-7 text-center">
        {/* Padding for days before the 1st */}
        {Array.from({ length: startPad }).map((_, i) => (
          <div key={`pad-${i}`} className="py-2" />
        ))}
        {days.map(({ day, isSunday, offering, isMissing, isToday, isFuture }) => {
          const t = offering ? rowTotal(offering) : 0
          return (
            <div
              key={day}
              onClick={() => offering && onSelectDate(offering.id)}
              className={`py-1.5 px-0.5 text-xs transition-colors relative ${
                offering ? 'cursor-pointer hover:bg-primary/10' : ''
              } ${isToday ? 'ring-1 ring-primary ring-inset' : ''} ${
                isFuture ? 'opacity-30' : ''
              }`}
            >
              <div className={`${isSunday ? 'font-bold' : ''} ${
                offering ? 'text-success' : isMissing ? 'text-warning' : isSunday ? 'text-primary' : 'text-muted'
              }`}>
                {day}
              </div>
              {offering && (
                <div className="text-[8px] text-success font-medium truncate">
                  ${t.toFixed(0)}
                </div>
              )}
              {isMissing && (
                <div className="text-[8px] text-warning">missing</div>
              )}
              {isSunday && !offering && !isMissing && !isFuture && (
                <div className="w-1.5 h-1.5 rounded-full bg-primary/30 mx-auto mt-0.5" />
              )}
            </div>
          )
        })}
      </div>
      {/* Legend */}
      <div className="flex items-center justify-center gap-4 py-1.5 border-t border-border text-[9px] text-muted">
        <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-success" /> Has offering</span>
        <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-warning" /> Missing Sunday</span>
        <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-primary/30" /> Sunday (future)</span>
      </div>
    </div>
  )
}

export function ReportsPage() {
  const navigate = useNavigate()
  const now = new Date()
  const [viewMode, setViewMode] = useState<ViewMode>('monthly')
  const [month, setMonth] = useState(now.getMonth())
  const [year, setYear] = useState(now.getFullYear())
  const [dateFrom, setDateFrom] = useState('')
  const [dateTo, setDateTo] = useState('')
  const { data: defaultRecipients } = useQuery({
    queryKey: ['settings', 'report_recipients'],
    queryFn: async () => {
      const { data } = await supabase.from('app_settings').select('value').eq('key', 'report_recipients').single()
      return data?.value || ''
    },
  })

  const [expandedId, setExpandedId] = useState<number | null>(null)
  const [sortKey, setSortKey] = useState<SortKey>('offering_date')
  const [sortDir, setSortDir] = useState<SortDir>('asc')
  const [filterText, setFilterText] = useState('')

  const [emailSending, setEmailSending] = useState(false)
  const [emailTarget, setEmailTarget] = useState<{ type: string; offering?: ApprovedOffering } | null>(null)
  const [emailRecipients, setEmailRecipients] = useState('')
  const [showMissing, setShowMissing] = useState(true)
  const [displayMode, setDisplayMode] = useState<'table' | 'cards'>('table')

  const { data: churchName } = useQuery({
    queryKey: ['settings', 'church_name'],
    queryFn: async () => {
      const { data } = await supabase.from('app_settings').select('value').eq('key', 'church_name').single()
      return data?.value || 'Offering Report'
    },
  })

  const accentColors = useAccentColors()

  const { data: allApproved, isLoading } = useQuery({
    queryKey: ['offerings', 'approved'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('offerings')
        .select('id, filename, offering_date, general, cash, sunday_school, building_fund, misc, notes, approved_by_email, locked_at')
        .eq('status', 'approved')
      if (error) throw error
      return data as ApprovedOffering[]
    },
  })

  const offerings = useMemo(() => {
    let filtered = (allApproved || []).filter(o => {
      const d = parseOfferingDate(o.offering_date)
      if (!d) return false
      if (viewMode === 'monthly') {
        return d.getMonth() === month && d.getFullYear() === year
      } else if (viewMode === 'yearly') {
        return d.getFullYear() === year
      } else {
        const from = dateFrom ? new Date(dateFrom) : null
        const to = dateTo ? new Date(dateTo + 'T23:59:59') : null
        if (from && d < from) return false
        if (to && d > to) return false
        return true
      }
    })

    if (filterText) {
      const q = filterText.toLowerCase()
      filtered = filtered.filter(o =>
        (o.offering_date || '').toLowerCase().includes(q) ||
        (o.filename || '').toLowerCase().includes(q) ||
        (o.notes || '').toLowerCase().includes(q) ||
        rowTotal(o).toFixed(2).includes(q)
      )
    }

    filtered.sort((a, b) => {
      let va: number, vb: number
      if (sortKey === 'offering_date') {
        va = parseOfferingDate(a.offering_date)?.getTime() || 0
        vb = parseOfferingDate(b.offering_date)?.getTime() || 0
      } else if (sortKey === 'total') {
        va = rowTotal(a); vb = rowTotal(b)
      } else {
        va = (a[sortKey] as number) || 0; vb = (b[sortKey] as number) || 0
      }
      return sortDir === 'asc' ? va - vb : vb - va
    })
    return filtered
  }, [allApproved, month, year, dateFrom, dateTo, viewMode, sortKey, sortDir, filterText])

  const toggleSort = (key: SortKey) => {
    if (sortKey === key) setSortDir(d => d === 'asc' ? 'desc' : 'asc')
    else { setSortKey(key); setSortDir(key === 'offering_date' ? 'asc' : 'desc') }
  }

  const prevMonth = () => { if (month === 0) { setMonth(11); setYear(y => y - 1) } else setMonth(m => m - 1) }
  const nextMonth = () => { if (month === 11) { setMonth(0); setYear(y => y + 1) } else setMonth(m => m + 1) }

  // Find missing Sundays (monthly and yearly views, only past dates)
  const missingSundays = useMemo(() => {
    if (viewMode === 'range') return []
    const sundays: string[] = []
    const today = new Date()
    today.setHours(23, 59, 59)
    const startMonth = viewMode === 'yearly' ? 0 : month
    const endMonth = viewMode === 'yearly' ? 11 : month
    const d = new Date(year, startMonth, 1)
    const endDate = new Date(year, endMonth + 1, 0)
    while (d <= endDate) {
      if (d.getDay() === 0 && d <= today) {
        const mm = String(d.getMonth() + 1).padStart(2, '0')
        const dd = String(d.getDate()).padStart(2, '0')
        sundays.push(`${mm}/${dd}/${d.getFullYear()}`)
      }
      d.setDate(d.getDate() + 1)
    }
    // Compare by parsed date (not string) to handle format differences
    const offeringTimestamps = new Set(
      offerings.map(o => parseOfferingDate(o.offering_date)?.toDateString()).filter(Boolean)
    )
    return sundays.filter(s => {
      const parsed = parseOfferingDate(s)
      return parsed && !offeringTimestamps.has(parsed.toDateString())
    })
  }, [offerings, month, year, viewMode])

  // Merge offerings and missing Sundays for display
  type DisplayRow = { type: 'offering'; data: ApprovedOffering } | { type: 'missing'; date: string }
  const displayRows = useMemo((): DisplayRow[] => {
    const rows: DisplayRow[] = offerings.map(o => ({ type: 'offering' as const, data: o }))
    if (showMissing) {
      for (const date of missingSundays) {
        rows.push({ type: 'missing' as const, date })
      }
    }
    rows.sort((a, b) => {
      const dateA = a.type === 'offering' ? a.data.offering_date : a.date
      const dateB = b.type === 'offering' ? b.data.offering_date : b.date
      const da = parseOfferingDate(dateA || '')?.getTime() || 0
      const db = parseOfferingDate(dateB || '')?.getTime() || 0
      return da - db
    })
    return rows
  }, [offerings, missingSundays, showMissing])

  const grandTotal = offerings.reduce((acc, o) => ({
    general: acc.general + (o.general || 0), cash: acc.cash + (o.cash || 0),
    sunday_school: acc.sunday_school + (o.sunday_school || 0),
    building_fund: acc.building_fund + (o.building_fund || 0), misc: acc.misc + (o.misc || 0),
  }), { general: 0, cash: 0, sunday_school: 0, building_fund: 0, misc: 0 })

  const grandTotalSum = grandTotal.general + grandTotal.cash + grandTotal.sunday_school +
    grandTotal.building_fund + grandTotal.misc

  const periodLabel = viewMode === 'monthly'
    ? `${MONTHS[month]} ${year}`
    : viewMode === 'yearly'
    ? `${year}`
    : `${dateFrom || 'Start'} to ${dateTo || 'End'}`

  const title = churchName || 'Offering Report'

  // Export functions
  const printReport = async () => {
    const today = new Date().toISOString().split('T')[0]
    try {
      await generateAndDownloadPdf({
        title,
        subtitle: periodLabel,
        headers: ['Date', 'General', 'Cash', 'Sunday School', 'Building Fund', 'Misc', 'Total'],
        rows: offerings.map(o => [formatDate(o.offering_date), fmt(o.general), fmt(o.cash), fmt(o.sunday_school), fmt(o.building_fund), fmt(o.misc), '$' + rowTotal(o).toFixed(2)]),
        footer_row: ['Total', '$' + grandTotal.general.toFixed(2), '$' + grandTotal.cash.toFixed(2), '$' + grandTotal.sunday_school.toFixed(2), '$' + grandTotal.building_fund.toFixed(2), '$' + grandTotal.misc.toFixed(2), '$' + grandTotalSum.toFixed(2)],
        accent_color: accentColors.report || '#16a34a',
        filename: 'ots_report_' + periodLabel.replace(/\s+/g, '_').toLowerCase() + '_' + today + '.pdf',
      })
    } catch (err) { alert(err instanceof Error ? err.message : 'PDF failed') }
  }

  // Initialize email recipients from defaults when target changes
  useEffect(() => {
    if (emailTarget && defaultRecipients && !emailRecipients) {
      setEmailRecipients(defaultRecipients)
    }
  }, [emailTarget, defaultRecipients])

  const sendEmail = async (subject: string, htmlBody: string) => {
    if (!emailRecipients.trim()) return
    setEmailSending(true)
    try {
      const resp = await fetch((await getBackendUrl()) + '/api/email/send', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          to: emailRecipients.split(',').map((e: string) => e.trim()).filter(Boolean),
          subject,
          html_body: htmlBody,
        }),
      })
      const data = await resp.json()
      if (data.success) { setEmailTarget(null); setEmailRecipients('') }
      else alert(data.detail || data.error || 'Send failed')
    } catch (err) { alert(err instanceof Error ? err.message : 'Failed') }
    finally { setEmailSending(false) }
  }

  const buildEmailReportHtml = () => {
    const rc = accentColors.report || '#16a34a'
    const thStyle = 'padding:10px 12px;text-align:right;font-size:11px;text-transform:uppercase;color:#64748b;border-bottom:2px solid #cbd5e1'
    const tdStyle = 'padding:8px 12px;text-align:right;border-bottom:1px solid #e5e7eb'
    const ftStyle = 'padding:10px 12px;text-align:right;font-weight:bold'
    const rows = offerings.map((o, i) => {
      const bg = i % 2 === 0 ? '#ffffff' : '#f8fafc'
      return '<tr style="background:' + bg + '"><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">' + formatDate(o.offering_date) + '</td>' +
        '<td style="' + tdStyle + '">' + fmt(o.general) + '</td><td style="' + tdStyle + '">' + fmt(o.cash) + '</td>' +
        '<td style="' + tdStyle + '">' + fmt(o.sunday_school) + '</td><td style="' + tdStyle + '">' + fmt(o.building_fund) + '</td>' +
        '<td style="' + tdStyle + '">' + fmt(o.misc) + '</td><td style="' + tdStyle + ';font-weight:bold">$' + rowTotal(o).toFixed(2) + '</td></tr>'
    }).join('')
    return '<div style="font-family:system-ui,sans-serif;max-width:700px;margin:0 auto;color:#1a1a2e">' +
      '<div style="background:' + rc + ';color:white;padding:20px 24px;border-radius:8px 8px 0 0"><h1 style="margin:0;font-size:18px">' + title + '</h1><p style="margin:4px 0 0;font-size:13px;opacity:0.85">' + periodLabel + '</p></div>' +
      '<div style="border:1px solid #e5e7eb;border-top:none;border-radius:0 0 8px 8px;overflow:hidden">' +
      '<table style="width:100%;border-collapse:collapse;font-size:13px;table-layout:fixed">' +
      '<colgroup><col style="width:22%"/><col style="width:13%"/><col style="width:13%"/><col style="width:13%"/><col style="width:13%"/><col style="width:13%"/><col style="width:13%"/></colgroup>' +
      '<thead><tr style="background:#f1f5f9">' +
      '<th style="' + thStyle + ';text-align:left">Date</th><th style="' + thStyle + '">General</th><th style="' + thStyle + '">Cash</th><th style="' + thStyle + '">Sunday School</th><th style="' + thStyle + '">Building Fund</th><th style="' + thStyle + '">Misc</th><th style="' + thStyle + '">Total</th>' +
      '</tr></thead><tbody>' + rows + '</tbody><tfoot><tr style="background:' + rc + ';color:white">' +
      '<td style="' + ftStyle + ';text-align:left">Total</td><td style="' + ftStyle + '">$' + grandTotal.general.toFixed(2) + '</td><td style="' + ftStyle + '">$' + grandTotal.cash.toFixed(2) + '</td><td style="' + ftStyle + '">$' + grandTotal.sunday_school.toFixed(2) + '</td><td style="' + ftStyle + '">$' + grandTotal.building_fund.toFixed(2) + '</td><td style="' + ftStyle + '">$' + grandTotal.misc.toFixed(2) + '</td><td style="' + ftStyle + '">$' + grandTotalSum.toFixed(2) + '</td>' +
      '</tr></tfoot></table></div><p style="margin-top:16px;font-size:10px;color:#94a3b8;text-align:center">Generated by OTS</p></div>'
  }

  const exportCsv = () => {
    const headers = 'Date,General,Cash,Sunday School,Building Fund,Miscellaneous,Total\n'
    const rows = offerings.map(o =>
      `${o.offering_date || ''},${o.general},${o.cash},${o.sunday_school},${o.building_fund},${o.misc},${rowTotal(o)}`
    ).join('\n')
    const totalsRow = `Total,${grandTotal.general},${grandTotal.cash},${grandTotal.sunday_school},${grandTotal.building_fund},${grandTotal.misc},${grandTotalSum}`
    const blob = new Blob([headers + rows + '\n' + totalsRow], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a'); a.href = url; a.download = `offerings_${periodLabel.replace(/\s+/g, '_').toLowerCase()}.csv`
    a.click(); URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Reports</h1>
          <p className="text-muted text-sm">{title} — {viewMode === 'monthly' ? 'Monthly' : viewMode === 'yearly' ? 'Yearly' : 'Date Range'} Report</p>
        </div>
      </div>

      {/* View mode toggle + date controls */}
      <div className="flex items-center gap-4 flex-wrap">
        <div className="flex gap-1 bg-card border border-border rounded-lg p-0.5">
          <button onClick={() => setViewMode('monthly')}
            className={`px-3 py-1.5 text-xs font-medium rounded-md cursor-pointer transition-colors ${
              viewMode === 'monthly' ? 'bg-primary text-primary-foreground' : 'text-muted hover:text-foreground'
            }`}>Monthly</button>
          <button onClick={() => setViewMode('yearly')}
            className={`px-3 py-1.5 text-xs font-medium rounded-md cursor-pointer transition-colors ${
              viewMode === 'yearly' ? 'bg-primary text-primary-foreground' : 'text-muted hover:text-foreground'
            }`}>Yearly</button>
          <button onClick={() => setViewMode('range')}
            className={`px-3 py-1.5 text-xs font-medium rounded-md cursor-pointer transition-colors flex items-center gap-1 ${
              viewMode === 'range' ? 'bg-primary text-primary-foreground' : 'text-muted hover:text-foreground'
            }`}><CalendarRange className="w-3 h-3" /> Range</button>
        </div>

        {viewMode === 'monthly' ? (
          <div className="flex items-center gap-3">
            <button onClick={prevMonth} className="p-1.5 rounded-lg border border-border hover:bg-muted-foreground/10 cursor-pointer">
              <ChevronLeft className="w-4 h-4" />
            </button>
            <div className="text-center min-w-[150px]">
              <p className="text-sm font-bold">{MONTHS[month]} {year}</p>
            </div>
            <button onClick={nextMonth} className="p-1.5 rounded-lg border border-border hover:bg-muted-foreground/10 cursor-pointer">
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        ) : viewMode === 'yearly' ? (
          <div className="flex items-center gap-3">
            <button onClick={() => setYear(y => y - 1)} className="p-1.5 rounded-lg border border-border hover:bg-muted-foreground/10 cursor-pointer">
              <ChevronLeft className="w-4 h-4" />
            </button>
            <div className="text-center min-w-[80px]">
              <p className="text-sm font-bold">{year}</p>
            </div>
            <button onClick={() => setYear(y => y + 1)} className="p-1.5 rounded-lg border border-border hover:bg-muted-foreground/10 cursor-pointer">
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        ) : (
          <div className="flex items-center gap-2">
            <input type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)}
              className="px-3 py-1.5 text-sm rounded-lg border border-border bg-background" />
            <span className="text-xs text-muted">to</span>
            <input type="date" value={dateTo} onChange={e => setDateTo(e.target.value)}
              className="px-3 py-1.5 text-sm rounded-lg border border-border bg-background" />
          </div>
        )}

        <span className="text-xs text-muted">
          {offerings.length} offering{offerings.length !== 1 ? 's' : ''}
          {missingSundays.length > 0 && (
            <button onClick={() => setShowMissing(!showMissing)}
              className={`ml-2 cursor-pointer ${showMissing ? 'text-warning' : 'text-muted line-through'}`}>
              {missingSundays.length} missing {showMissing ? '(hide)' : '(show)'}
            </button>
          )}
        </span>
      </div>

      {/* Month calendar view (monthly mode only) */}
      {viewMode === 'monthly' && !isLoading && (
        <MonthCalendar
          year={year}
          month={month}
          offerings={offerings}
          missingSundays={missingSundays}
          onSelectDate={(offeringId) => {
            if (offeringId) setExpandedId(expandedId === offeringId ? null : offeringId)
          }}
        />
      )}

      {isLoading ? (
        <div className="flex justify-center py-10"><Loader2 className="w-6 h-6 animate-spin text-primary" /></div>
      ) : offerings.length > 0 ? (
        <>
          {/* Summary cards */}
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
            {[
              { label: 'General', value: grandTotal.general, color: 'text-blue-500' },
              { label: 'Cash', value: grandTotal.cash, color: 'text-green-500' },
              { label: 'Sunday School', value: grandTotal.sunday_school, color: 'text-purple-500' },
              { label: 'Building Fund', value: grandTotal.building_fund, color: 'text-orange-500' },
              { label: 'Miscellaneous', value: grandTotal.misc, color: 'text-muted' },
              { label: 'Total', value: grandTotalSum, color: 'text-primary' },
            ].map(({ label, value, color }) => (
              <div key={label} className="rounded-lg border border-border bg-card p-3 text-center">
                <p className="text-[10px] text-muted uppercase tracking-wider">{label}</p>
                <p className={`text-lg font-bold ${color}`}>${value.toFixed(2)}</p>
              </div>
            ))}
          </div>

          {/* Year-to-date summary */}
          {(() => {
            const currentYear = viewMode === 'monthly' ? year : new Date().getFullYear()
            const ytdOfferings = (allApproved || []).filter(o => {
              const d = parseOfferingDate(o.offering_date)
              return d && d.getFullYear() === currentYear
            })
            const ytd = ytdOfferings.reduce((acc, o) => ({
              general: acc.general + (o.general || 0), cash: acc.cash + (o.cash || 0),
              sunday_school: acc.sunday_school + (o.sunday_school || 0),
              building_fund: acc.building_fund + (o.building_fund || 0), misc: acc.misc + (o.misc || 0),
            }), { general: 0, cash: 0, sunday_school: 0, building_fund: 0, misc: 0 })
            const ytdTotal = ytd.general + ytd.cash + ytd.sunday_school + ytd.building_fund + ytd.misc

            return ytdTotal > 0 ? (
              <div className="rounded-lg border border-border/50 bg-card/50 px-4 py-2.5 flex items-center justify-between">
                <span className="text-xs text-muted">Year-to-Date ({currentYear}): {ytdOfferings.length} offerings</span>
                <div className="flex items-center gap-4 text-xs">
                  <span>General: <strong>${ytd.general.toFixed(0)}</strong></span>
                  <span>Cash: <strong>${ytd.cash.toFixed(0)}</strong></span>
                  <span>SS: <strong>${ytd.sunday_school.toFixed(0)}</strong></span>
                  <span>BF: <strong>${ytd.building_fund.toFixed(0)}</strong></span>
                  {ytd.misc > 0 && <span>Misc: <strong>${ytd.misc.toFixed(0)}</strong></span>}
                  <span className="text-primary font-bold">Total: ${ytdTotal.toFixed(2)}</span>
                </div>
              </div>
            ) : null
          })()}

          {/* Filter + Export bar */}
          <div className="flex items-center justify-between gap-3 flex-wrap">
            <div className="relative flex-1 max-w-xs">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted" />
              <input type="text" placeholder="Filter..."
                value={filterText} onChange={e => setFilterText(e.target.value)}
                className="w-full pl-9 pr-3 py-1.5 text-sm rounded-lg border border-border bg-background" />
            </div>
            <div className="flex gap-2 flex-wrap">
              <button onClick={printReport}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 cursor-pointer">
                <Printer className="w-3.5 h-3.5" /> PDF
              </button>
              <button onClick={() => setDisplayMode(displayMode === 'cards' ? 'table' : 'cards')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm cursor-pointer ${
                  displayMode === 'cards' ? 'bg-primary text-primary-foreground' : 'border border-border hover:bg-muted-foreground/10'
                }`}>
                <Share2 className="w-3.5 h-3.5" /> {displayMode === 'cards' ? 'Table' : 'Cards'}
              </button>
              <button onClick={exportCsv}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border hover:bg-muted-foreground/10 text-sm cursor-pointer">
                <Download className="w-3.5 h-3.5" /> CSV
              </button>
              <button onClick={async () => {
                  // Build full styled HTML document for PDF conversion
                  const rc = accentColors.report || '#16a34a'
                  const tableHtml = buildReportTable(offerings, grandTotal, grandTotalSum)
                  const fullHtml = '<!DOCTYPE html><html><head><style>' +
                    'body{font-family:system-ui,sans-serif;margin:30px;color:#1a1a2e}' +
                    'h1{font-size:18px;margin:0 0 4px;color:' + rc + '}' +
                    'h2{font-size:13px;color:#64748b;font-weight:normal;margin:0 0 20px}' +
                    'table{width:100%;border-collapse:collapse;font-size:12px}' +
                    'th{padding:8px 10px;text-align:right;font-size:10px;text-transform:uppercase;color:#64748b;border-bottom:2px solid ' + rc + ';background:#f1f5f9}' +
                    'th:first-child{text-align:left}' +
                    'td{padding:6px 10px;text-align:right;border-bottom:1px solid #e5e7eb}' +
                    'td:first-child{text-align:left}' +
                    'tr:nth-child(even){background:#f8fafc}' +
                    'tfoot tr{background:' + rc + ';color:white}' +
                    'tfoot td{font-weight:bold;border:none;padding:8px 10px}' +
                    '.footer{margin-top:20px;font-size:9px;color:#94a3b8}' +
                    '</style></head><body>' +
                    '<h1>' + title + '</h1>' +
                    '<h2>' + periodLabel + '</h2>' +
                    tableHtml +
                    '<p class="footer">Generated by OTS on ' + new Date().toLocaleDateString() + '</p>' +
                    '</body></html>'
                  try {
                    const resp = await fetch((await getBackendUrl()) + '/api/drive/upload-report', {
                      method: 'POST',
                      headers: { 'Content-Type': 'application/json' },
                      body: JSON.stringify({
                        filename: 'OTS_Report_' + periodLabel.replace(/\s+/g, '_') + '.pdf',
                        content_base64: btoa(unescape(encodeURIComponent(fullHtml))),
                        mime_type: 'text/html',
                      }),
                    })
                    const data = await resp.json()
                    if (data.success) alert('PDF report uploaded to Drive: ' + data.name)
                    else alert(data.detail || data.error || 'Upload failed')
                  } catch (err) { alert(err instanceof Error ? err.message : 'Failed') }
                }}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border hover:bg-muted-foreground/10 text-sm cursor-pointer">
                <CloudUpload className="w-3.5 h-3.5" /> Drive
              </button>
              <button onClick={() => setEmailTarget(emailTarget?.type === 'report' ? null : { type: 'report' })}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm cursor-pointer ${
                  emailTarget?.type === 'report' ? 'bg-primary text-primary-foreground' : 'border border-border hover:bg-muted-foreground/10'
                }`}>
                <Mail className="w-3.5 h-3.5" /> Email
              </button>
            </div>
          </div>

          {/* Inline email panel */}
          {emailTarget && (
            <div className="rounded-xl border border-primary/30 bg-primary/5 p-4">
              <div className="flex items-center gap-3">
                <Mail className="w-4 h-4 text-primary flex-shrink-0" />
                <input type="text" placeholder="Recipients (comma-separated emails)"
                  value={emailRecipients}
                  onChange={e => setEmailRecipients(e.target.value)}
                  className="flex-1 px-3 py-1.5 text-sm rounded-lg border border-border bg-background" />
                <button disabled={emailSending || !emailRecipients.trim()}
                  onClick={() => {
                    const o = emailTarget.offering
                    if (emailTarget.type === 'report') {
                      sendEmail(title + ' — ' + periodLabel, buildEmailReportHtml())
                    } else if (o) {
                      sendEmail(title + ' — Week of ' + formatDate(o.offering_date), buildEmailCard(title, o, accentColors.card))
                    }
                  }}
                  className="flex items-center gap-1.5 px-4 py-1.5 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 cursor-pointer disabled:opacity-50">
                  {emailSending ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Mail className="w-3.5 h-3.5" />}
                  Send
                </button>
                <button onClick={() => { setEmailTarget(null); setEmailRecipients('') }}
                  className="text-xs text-muted hover:text-foreground cursor-pointer">Cancel</button>
              </div>
              <p className="text-[10px] text-muted mt-1.5 ml-8">
                {emailTarget.type === 'report' ? 'Sending full report table' : 'Sending weekly offering card for ' + formatDate(emailTarget.offering?.offering_date || '')}
              </p>
            </div>
          )}

          {/* Cards view (inline) */}
          {displayMode === 'cards' && (
            <div>
              {/* Period summary card */}
              <div className="rounded-xl border border-primary/30 bg-primary/5 p-5 mb-4">
                <h2 className="text-lg font-bold text-primary">{title}</h2>
                <p className="text-sm text-muted">{periodLabel} — {offerings.length} offering{offerings.length !== 1 ? 's' : ''}</p>
                <div className="flex gap-6 mt-3 text-sm">
                  <span>General: <strong>${grandTotal.general.toFixed(2)}</strong></span>
                  <span>Cash: <strong>${grandTotal.cash.toFixed(2)}</strong></span>
                  {grandTotal.sunday_school > 0 && <span>SS: <strong>${grandTotal.sunday_school.toFixed(2)}</strong></span>}
                  {grandTotal.building_fund > 0 && <span>BF: <strong>${grandTotal.building_fund.toFixed(2)}</strong></span>}
                  {grandTotal.misc > 0 && <span>Misc: <strong>${grandTotal.misc.toFixed(2)}</strong></span>}
                  <span className="text-primary font-bold">Total: ${grandTotalSum.toFixed(2)}</span>
                </div>
              </div>

              {/* Individual week cards */}
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                {offerings.map(o => {
                  const t = rowTotal(o)
                  return (
                    <div key={o.id} className="rounded-xl border border-border overflow-hidden hover:border-primary/30 transition-colors">
                      <div className="bg-card px-4 py-3 border-b border-border">
                        <p className="text-sm font-bold">{formatDate(o.offering_date)}</p>
                        <p className="text-[10px] text-muted">Week offering</p>
                      </div>
                      <div className="px-4 py-3 space-y-1.5">
                        {o.general > 0 && (
                          <div className="flex justify-between text-sm">
                            <span className="text-muted">General (Checks)</span>
                            <span>${o.general.toFixed(2)}</span>
                          </div>
                        )}
                        {o.cash > 0 && (
                          <div className="flex justify-between text-sm">
                            <span className="text-muted">Cash</span>
                            <span>${o.cash.toFixed(2)}</span>
                          </div>
                        )}
                        {o.sunday_school > 0 && (
                          <div className="flex justify-between text-sm">
                            <span className="text-muted">Sunday School</span>
                            <span>${o.sunday_school.toFixed(2)}</span>
                          </div>
                        )}
                        {o.building_fund > 0 && (
                          <div className="flex justify-between text-sm">
                            <span className="text-muted">Building Fund</span>
                            <span>${o.building_fund.toFixed(2)}</span>
                          </div>
                        )}
                        {o.misc > 0 && (
                          <div className="flex justify-between text-sm">
                            <span className="text-muted">Miscellaneous</span>
                            <span>${o.misc.toFixed(2)}</span>
                          </div>
                        )}
                        <div className="flex justify-between text-sm font-bold pt-1.5 border-t border-border">
                          <span>Total</span>
                          <span className="text-primary">${t.toFixed(2)}</span>
                        </div>
                      </div>
                      <div className="px-4 py-2 border-t border-border flex gap-2">
                        <button onClick={() => navigate(`/review?id=${o.id}`)}
                          className="flex items-center gap-1 px-2 py-1 text-[10px] rounded border border-border hover:bg-muted-foreground/10 cursor-pointer">
                          <ExternalLink className="w-3 h-3" /> Review
                        </button>
                        <button onClick={() => setEmailTarget(emailTarget?.offering?.id === o.id ? null : { type: 'card', offering: o })}
                          className="flex items-center gap-1 px-2 py-1 text-[10px] rounded border border-border hover:bg-muted-foreground/10 cursor-pointer">
                          <Mail className="w-3 h-3" /> Email
                        </button>
                      </div>
                    </div>
                  )
                })}
              </div>

              {/* Missing Sundays */}
              {showMissing && missingSundays.length > 0 && (
                <div className="mt-4 space-y-2">
                  {missingSundays.map(date => (
                    <div key={date} className="flex items-center gap-2 px-4 py-2 rounded-lg bg-warning/5 border border-warning/20">
                      <span className="w-3 h-3 rounded-full bg-warning/30" />
                      <span className="text-sm text-warning">{date} — No offering recorded</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* Sortable data table */}
          {displayMode === 'table' && <div className="rounded-xl border border-border overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-sm table-fixed">
                <colgroup>
                  <col className="w-[130px]" /> {/* Date */}
                  <col /> {/* General */}
                  <col /> {/* Cash */}
                  <col /> {/* Sunday School */}
                  <col /> {/* Building Fund */}
                  <col /> {/* Miscellaneous */}
                  <col /> {/* Total */}
                </colgroup>
                <thead>
                  <tr className="bg-card border-b border-border">
                    {COLUMNS.map(col => (
                      <th key={col.key} onClick={() => toggleSort(col.key)}
                        className={`px-3 py-3 text-xs font-medium text-muted cursor-pointer hover:text-foreground select-none transition-colors ${
                          col.key === 'offering_date' ? 'text-left' : 'text-right'
                        }`}>
                        <span className="inline-flex items-center gap-1">
                          {col.label}
                          {sortKey === col.key ? (
                            sortDir === 'asc' ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />
                          ) : (
                            <ArrowUpDown className="w-3 h-3 opacity-30" />
                          )}
                        </span>
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {displayRows.map((row) => {
                    if (row.type === 'missing') {
                      return (
                        <tr key={`missing-${row.date}`} className="bg-warning/5">
                          <td className="px-3 py-2 font-medium text-warning">
                            <div className="flex items-center gap-1.5">
                              <span className="w-3 h-3 rounded-full bg-warning/30 flex-shrink-0" />
                              {row.date}
                            </div>
                          </td>
                          <td colSpan={6} className="px-3 py-2 text-xs text-warning italic">
                            No offering recorded for this Sunday
                          </td>
                        </tr>
                      )
                    }
                    const o = row.data
                    return (
                      <React.Fragment key={o.id}>
                        <tr onClick={() => setExpandedId(expandedId === o.id ? null : o.id)}
                          className="hover:bg-muted-foreground/5 cursor-pointer">
                          <td className="px-3 py-2.5 font-medium">
                            <div className="flex items-center gap-1.5">
                              {expandedId === o.id ? <ChevronUp className="w-3 h-3 text-muted" /> : <ChevronDown className="w-3 h-3 text-muted" />}
                              {formatDate(o.offering_date)}
                            </div>
                          </td>
                          <td className="px-3 py-2.5 text-right">{fmt(o.general)}</td>
                          <td className="px-3 py-2.5 text-right">{fmt(o.cash)}</td>
                          <td className="px-3 py-2.5 text-right">{fmt(o.sunday_school)}</td>
                          <td className="px-3 py-2.5 text-right">{fmt(o.building_fund)}</td>
                          <td className="px-3 py-2.5 text-right">{fmt(o.misc)}</td>
                          <td className="px-3 py-2.5 text-right font-bold">${rowTotal(o).toFixed(2)}</td>
                        </tr>
                        {expandedId === o.id && (
                          <tr>
                            <td colSpan={7} className="px-4 py-3 bg-card/50">
                              <div className="flex items-start justify-between gap-4">
                                <div className="space-y-1 text-xs">
                                  <p className="font-medium text-sm mb-2">Week of {formatDate(o.offering_date)}</p>
                                  {o.general > 0 && <p>General (Checks): <strong>${o.general.toFixed(2)}</strong></p>}
                                  {o.cash > 0 && <p>Cash (Denominations): <strong>${o.cash.toFixed(2)}</strong></p>}
                                  {o.sunday_school > 0 && <p>Sunday School: <strong>${o.sunday_school.toFixed(2)}</strong></p>}
                                  {o.building_fund > 0 && <p>Building Fund: <strong>${o.building_fund.toFixed(2)}</strong></p>}
                                  {o.misc > 0 && <p>Miscellaneous: <strong>${o.misc.toFixed(2)}</strong></p>}
                                  <p className="pt-1 font-bold">Total: ${rowTotal(o).toFixed(2)}</p>
                                  {o.notes && <p className="text-muted pt-1">{o.notes}</p>}
                                </div>
                                <div className="flex gap-2 flex-shrink-0">
                                  <button onClick={e => { e.stopPropagation(); navigate(`/review?id=${o.id}`) }}
                                    className="flex items-center gap-1 px-2 py-1 text-xs rounded border border-border hover:bg-muted-foreground/10 cursor-pointer">
                                    <ExternalLink className="w-3 h-3" /> View
                                  </button>
                                  <button onClick={e => { e.stopPropagation(); setEmailTarget(emailTarget?.offering?.id === o.id ? null : { type: 'card', offering: o }) }}
                                    className="flex items-center gap-1 px-2 py-1 text-xs rounded border border-border hover:bg-muted-foreground/10 cursor-pointer">
                                    <Mail className="w-3 h-3" /> Email Card
                                  </button>
                                </div>
                              </div>
                            </td>
                          </tr>
                        )}
                      </React.Fragment>
                    )
                  })}
                </tbody>
                <tfoot>
                  <tr className="bg-card border-t-2 border-border font-bold">
                    <td className="px-3 py-3">Total</td>
                    <td className="px-3 py-3 text-right">${grandTotal.general.toFixed(2)}</td>
                    <td className="px-3 py-3 text-right">${grandTotal.cash.toFixed(2)}</td>
                    <td className="px-3 py-3 text-right">${grandTotal.sunday_school.toFixed(2)}</td>
                    <td className="px-3 py-3 text-right">${grandTotal.building_fund.toFixed(2)}</td>
                    <td className="px-3 py-3 text-right">${grandTotal.misc.toFixed(2)}</td>
                    <td className="px-3 py-3 text-right text-primary">${grandTotalSum.toFixed(2)}</td>
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>}
        </>
      ) : (
        <div className="rounded-xl border border-border bg-card p-10 text-center">
          <FileText className="w-10 h-10 mx-auto text-muted mb-3" />
          <p className="text-muted">No approved offerings for {periodLabel}</p>
          <p className="text-xs text-muted mt-1">Upload and approve offerings to see them here</p>
        </div>
      )}
    </div>
  )
}
