import { getBackendUrl } from '@/lib/backend'
import React, { useState, useMemo, useEffect } from 'react'
import { useQuery } from '@tanstack/react-query'
import { useNavigate } from 'react-router-dom'
import { supabase } from '@/lib/supabase'
import {
  FileText, Download, Loader2, ChevronLeft, ChevronRight, Printer,
  ExternalLink, Share2, ChevronDown, ChevronUp, ArrowUpDown, Search,
  CalendarRange, CloudUpload, Mail, TrendingUp,
} from 'lucide-react'
import { generateAndDownloadPdf, generateAndUploadPdf } from '@/lib/pdf-utils'
import { useAccentColors } from '@/lib/accent-colors'


interface ApprovedOffering {
  id: number
  filename: string | null
  offering_date: string | null
  general: number
  cash: number
  sunday_school: number
  building_fund: number
  misc: number
  notes: string | null
  approved_by_email: string | null
  locked_at: string | null
}

type SortKey = 'offering_date' | 'general' | 'cash' | 'sunday_school' | 'building_fund' | 'misc' | 'total'
type SortDir = 'asc' | 'desc'
type ViewMode = 'monthly' | 'yearly' | 'range' | 'trends'

type Category = 'general' | 'cash' | 'sunday_school' | 'building_fund' | 'misc'

const ALL_CATS: { key: Category; label: string }[] = [
  { key: 'general', label: 'General' },
  { key: 'cash', label: 'Cash' },
  { key: 'sunday_school', label: 'Sunday School' },
  { key: 'building_fund', label: 'Building Fund' },
  { key: 'misc', label: 'Miscellaneous' },
]

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December']

const COLUMNS: { key: SortKey; label: string }[] = [
  { key: 'offering_date', label: 'Date' },
  { key: 'general', label: 'General' },
  { key: 'cash', label: 'Cash' },
  { key: 'sunday_school', label: 'Sunday School' },
  { key: 'building_fund', label: 'Building Fund' },
  { key: 'misc', label: 'Miscellaneous' },
  { key: 'total', label: 'Total' },
]

const parseOfferingDate = (d: string | null): Date | null => {
  if (!d) return null
  const slashMatch = d.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/)
  if (slashMatch) return new Date(+slashMatch[3], +slashMatch[1] - 1, +slashMatch[2])
  const isoMatch = d.match(/^(\d{4})-(\d{2})-(\d{2})/)
  if (isoMatch) return new Date(+isoMatch[1], +isoMatch[2] - 1, +isoMatch[3])
  return null
}

const formatDate = (d: string | null) => {
  if (!d) return '—'
  if (d.includes('/')) return d
  const [y, m, day] = d.split('-')
  return `${m}/${day}/${y}`
}

const fmt = (n: number) => n > 0 ? `$${n.toFixed(2)}` : '—'
const rowTotal = (o: ApprovedOffering) =>
  (o.general || 0) + (o.cash || 0) + (o.sunday_school || 0) + (o.building_fund || 0) + (o.misc || 0)

// Email-safe card using tables (Gmail/Outlook compatible), styled to match app card view.
function buildEmailCard(
  churchName: string,
  o: ApprovedOffering,
  catList: { key: Category; label: string }[],
  accent = '#4f46e5'
): string {
  const t = catList.reduce((sum, c) => sum + ((o as any)[c.key] || 0), 0)
  const row = (label: string, amount: number) =>
    '<tr>' +
      '<td style="padding:9px 20px;font-size:13px;color:#6b7280;border-bottom:1px solid #f1f5f9">' + label + '</td>' +
      '<td style="padding:9px 20px;font-size:13px;text-align:right;border-bottom:1px solid #f1f5f9;font-weight:600;color:#111827">$' + amount.toFixed(2) + '</td>' +
    '</tr>'

  let rows = ''
  for (const cat of catList) {
    if ((o as any)[cat.key] > 0) rows += row(cat.label, (o as any)[cat.key])
  }

  return (
    '<div style="max-width:400px;margin:0 auto;font-family:system-ui,-apple-system,sans-serif">' +
    '<table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e2e8f0;border-radius:10px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,0.07)">' +
      '<tr><td style="background:' + accent + ';padding:14px 20px 12px">' +
        '<div style="font-size:15px;font-weight:700;color:#ffffff;line-height:1.3">' + churchName + '</div>' +
        '<div style="font-size:11px;color:rgba(255,255,255,0.82);margin-top:3px">Week of ' + formatDate(o.offering_date) + '</div>' +
      '</td></tr>' +
      '<tr><td style="padding:0;background:#ffffff">' +
        '<table width="100%" cellpadding="0" cellspacing="0">' +
          rows +
          '<tr>' +
            '<td style="padding:12px 20px;font-size:14px;font-weight:700;color:' + accent + ';border-top:2px solid ' + accent + '">Total</td>' +
            '<td style="padding:12px 20px;font-size:14px;font-weight:700;color:' + accent + ';text-align:right;border-top:2px solid ' + accent + '">$' + t.toFixed(2) + '</td>' +
          '</tr>' +
        '</table>' +
      '</td></tr>' +
    '</table>' +
    '<p style="margin:10px 0 0;font-size:10px;color:#94a3b8;text-align:center">Generated by OTS · ' + new Date().toLocaleDateString() + '</p>' +
    '</div>'
  )
}


function TrendsTab({ allApproved }: { allApproved: ApprovedOffering[] }) {
  const now = useMemo(() => new Date(), [])
  const curYear = now.getFullYear()
  const [wowMonth, setWowMonth] = useState(now.getMonth())
  const [wowYear, setWowYear] = useState(now.getFullYear())

  const byYearMonth = useMemo(() => {
    const map = new Map<string, ApprovedOffering[]>()
    for (const o of allApproved) {
      const d = parseOfferingDate(o.offering_date)
      if (!d) continue
      const key = `${d.getFullYear()}-${d.getMonth()}`
      if (!map.has(key)) map.set(key, [])
      map.get(key)!.push(o)
    }
    return map
  }, [allApproved])

  const monthTotal = (y: number, m: number) =>
    (byYearMonth.get(`${y}-${m}`) || []).reduce((sum, o) => sum + rowTotal(o), 0)

  const last12 = useMemo(() => {
    const result: { year: number; month: number; total: number }[] = []
    for (let i = 11; i >= 0; i--) {
      let m = now.getMonth() - i
      let y = now.getFullYear()
      while (m < 0) { m += 12; y-- }
      result.push({ year: y, month: m, total: monthTotal(y, m) })
    }
    return result
  }, [byYearMonth, now])

  const maxMonthly = useMemo(() => Math.max(...last12.map(x => x.total), 1), [last12])

  const wowData = useMemo(() => {
    const curr = (byYearMonth.get(`${wowYear}-${wowMonth}`) || [])
      .sort((a, b) => (parseOfferingDate(a.offering_date)?.getTime() || 0) - (parseOfferingDate(b.offering_date)?.getTime() || 0))
    let pm = wowMonth - 1, py = wowYear
    if (pm < 0) { pm = 11; py-- }
    const prior = (byYearMonth.get(`${py}-${pm}`) || [])
      .sort((a, b) => (parseOfferingDate(a.offering_date)?.getTime() || 0) - (parseOfferingDate(b.offering_date)?.getTime() || 0))
    const prevLastWeek = prior.length > 0 ? rowTotal(prior[prior.length - 1]) : null
    return curr.map((o, i) => {
      const total = rowTotal(o)
      const prev = i === 0 ? prevLastWeek : rowTotal(curr[i - 1])
      const pct = prev && prev > 0 ? ((total - prev) / prev * 100) : null
      return { o, total, pct }
    })
  }, [byYearMonth, wowMonth, wowYear])

  const maxWow = useMemo(() => Math.max(...wowData.map(x => x.total), 1), [wowData])

  const yoyData = useMemo(() => Array.from({ length: 12 }, (_, m) => ({
    month: m,
    cur: monthTotal(curYear, m),
    prev: monthTotal(curYear - 1, m),
  })), [byYearMonth, curYear])

  const maxYoy = useMemo(() => Math.max(...yoyData.flatMap(x => [x.cur, x.prev]), 1), [yoyData])

  const allTotals = useMemo(() => allApproved.map(o => rowTotal(o)).filter(t => t > 0), [allApproved])
  const bestWeekTotal = allTotals.length > 0 ? Math.max(...allTotals) : 0
  const avgWeekTotal = allTotals.length > 0 ? allTotals.reduce((a, b) => a + b, 0) / allTotals.length : 0
  const bestWeekOffering = useMemo(
    () => allApproved.find(o => rowTotal(o) === bestWeekTotal),
    [allApproved, bestWeekTotal]
  )

  const curYearTotal = useMemo(() =>
    allApproved.filter(o => parseOfferingDate(o.offering_date)?.getFullYear() === curYear)
      .reduce((sum, o) => sum + rowTotal(o), 0),
    [allApproved, curYear]
  )
  const prevYearTotal = useMemo(() =>
    allApproved.filter(o => parseOfferingDate(o.offering_date)?.getFullYear() === curYear - 1)
      .reduce((sum, o) => sum + rowTotal(o), 0),
    [allApproved, curYear]
  )
  const yoyPct = prevYearTotal > 0 ? ((curYearTotal - prevYearTotal) / prevYearTotal * 100) : null

  if (allApproved.length === 0) {
    return (
      <div className="rounded-xl border border-border bg-card p-10 text-center">
        <TrendingUp className="w-10 h-10 mx-auto text-muted mb-3" />
        <p className="text-muted">No approved offerings yet</p>
        <p className="text-xs text-muted mt-1">Approve offerings to see trend analysis</p>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Key metrics */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="rounded-lg border border-border bg-card p-4">
          <p className="text-[10px] text-muted uppercase tracking-wider">Best Week</p>
          <p className="text-xl font-bold text-primary">${bestWeekTotal.toFixed(2)}</p>
          {bestWeekOffering && <p className="text-[10px] text-muted mt-0.5">{formatDate(bestWeekOffering.offering_date)}</p>}
        </div>
        <div className="rounded-lg border border-border bg-card p-4">
          <p className="text-[10px] text-muted uppercase tracking-wider">Weekly Average</p>
          <p className="text-xl font-bold">${avgWeekTotal.toFixed(2)}</p>
          <p className="text-[10px] text-muted mt-0.5">{allTotals.length} weeks total</p>
        </div>
        <div className="rounded-lg border border-border bg-card p-4">
          <p className="text-[10px] text-muted uppercase tracking-wider">{curYear} Total</p>
          <p className="text-xl font-bold">${curYearTotal.toFixed(2)}</p>
          {yoyPct !== null && (
            <p className={`text-[10px] mt-0.5 font-medium ${yoyPct >= 0 ? 'text-success' : 'text-destructive'}`}>
              {yoyPct >= 0 ? '+' : ''}{yoyPct.toFixed(1)}% vs {curYear - 1}
            </p>
          )}
        </div>
        <div className="rounded-lg border border-border bg-card p-4">
          <p className="text-[10px] text-muted uppercase tracking-wider">{curYear - 1} Total</p>
          <p className="text-xl font-bold">${prevYearTotal.toFixed(2)}</p>
          <p className="text-[10px] text-muted mt-0.5">Prior full year</p>
        </div>
      </div>

      {/* Monthly trend — last 12 months */}
      <div className="rounded-xl border border-border bg-card p-5">
        <h3 className="text-sm font-semibold mb-4">Monthly Totals — Last 12 Months</h3>
        <div className="space-y-1.5">
          {last12.map(({ year, month, total }, i) => {
            const prev = i > 0 ? last12[i - 1].total : null
            const pct = prev !== null && prev > 0 ? ((total - prev) / prev * 100) : null
            const barPct = total > 0 ? (total / maxMonthly * 100) : 0
            const isCurrent = year === now.getFullYear() && month === now.getMonth()
            return (
              <div key={`${year}-${month}`} className="flex items-center gap-2">
                <div className="w-16 text-right text-[10px] text-muted flex-shrink-0">
                  {MONTHS[month].slice(0, 3)}{year !== now.getFullYear() ? ` '${String(year).slice(2)}` : ''}
                </div>
                <div className={`flex-1 h-5 rounded overflow-hidden ${isCurrent ? 'bg-primary/20' : 'bg-border/40'}`}>
                  <div
                    className={`h-full rounded transition-all ${isCurrent ? 'bg-primary' : 'bg-primary/60'}`}
                    style={{ width: barPct + '%' }}
                  />
                </div>
                <div className="w-20 text-right text-xs font-medium flex-shrink-0">
                  {total > 0 ? `$${total.toFixed(0)}` : <span className="text-muted text-[10px]">—</span>}
                </div>
                <div className={`w-14 text-right text-[10px] font-medium flex-shrink-0 ${pct !== null ? (pct >= 0 ? 'text-success' : 'text-destructive') : ''}`}>
                  {pct !== null && total > 0 ? `${pct >= 0 ? '+' : ''}${pct.toFixed(1)}%` : ''}
                </div>
              </div>
            )
          })}
        </div>
      </div>

      {/* Week-over-week */}
      <div className="rounded-xl border border-border bg-card p-5">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-sm font-semibold">Week-over-Week — {MONTHS[wowMonth]} {wowYear}</h3>
          <div className="flex items-center gap-1">
            <button
              onClick={() => { let m = wowMonth - 1, y = wowYear; if (m < 0) { m = 11; y-- } setWowMonth(m); setWowYear(y) }}
              className="p-1 rounded border border-border hover:bg-muted-foreground/10 cursor-pointer"
            ><ChevronLeft className="w-3.5 h-3.5" /></button>
            <button
              onClick={() => { let m = wowMonth + 1, y = wowYear; if (m > 11) { m = 0; y++ } setWowMonth(m); setWowYear(y) }}
              className="p-1 rounded border border-border hover:bg-muted-foreground/10 cursor-pointer"
            ><ChevronRight className="w-3.5 h-3.5" /></button>
          </div>
        </div>
        {wowData.length === 0 ? (
          <p className="text-sm text-muted text-center py-4">No offerings recorded for {MONTHS[wowMonth]} {wowYear}</p>
        ) : (
          <div className="space-y-1.5">
            {wowData.map(({ o, total, pct }) => (
              <div key={o.id} className="flex items-center gap-2">
                <div className="w-20 text-right text-[10px] text-muted flex-shrink-0">{formatDate(o.offering_date)}</div>
                <div className="flex-1 h-5 bg-border/40 rounded overflow-hidden">
                  <div className="h-full rounded bg-primary/70 transition-all" style={{ width: (total / maxWow * 100) + '%' }} />
                </div>
                <div className="w-20 text-right text-xs font-medium flex-shrink-0">${total.toFixed(2)}</div>
                <div className={`w-14 text-right text-[10px] font-medium flex-shrink-0 ${pct !== null ? (pct >= 0 ? 'text-success' : 'text-destructive') : 'text-muted'}`}>
                  {pct !== null ? `${pct >= 0 ? '+' : ''}${pct.toFixed(1)}%` : 'first'}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Year-over-year */}
      {(curYearTotal > 0 || prevYearTotal > 0) && (
        <div className="rounded-xl border border-border bg-card p-5">
          <h3 className="text-sm font-semibold mb-4">Year-over-Year — {curYear} vs {curYear - 1}</h3>
          <div className="space-y-2">
            {yoyData.filter(({ cur, prev }) => cur > 0 || prev > 0).map(({ month, cur, prev }) => {
              const pct = prev > 0 ? ((cur - prev) / prev * 100) : null
              return (
                <div key={month} className="flex items-center gap-2">
                  <div className="w-8 text-right text-[10px] text-muted flex-shrink-0">{MONTHS[month].slice(0, 3)}</div>
                  <div className="flex-1 space-y-0.5">
                    <div className="h-4 bg-border/40 rounded overflow-hidden">
                      <div className="h-full rounded bg-primary/70" style={{ width: (cur / maxYoy * 100) + '%' }} />
                    </div>
                    <div className="h-4 bg-border/40 rounded overflow-hidden">
                      <div className="h-full rounded bg-muted-foreground/40" style={{ width: (prev / maxYoy * 100) + '%' }} />
                    </div>
                  </div>
                  <div className="w-20 text-right flex-shrink-0 space-y-0.5">
                    <div className="text-[10px] font-medium">{cur > 0 ? `$${cur.toFixed(0)}` : '—'}</div>
                    <div className="text-[10px] text-muted">{prev > 0 ? `$${prev.toFixed(0)}` : '—'}</div>
                  </div>
                  <div className={`w-14 text-right text-[10px] font-medium flex-shrink-0 ${pct !== null ? (pct >= 0 ? 'text-success' : 'text-destructive') : ''}`}>
                    {pct !== null && cur > 0 ? `${pct >= 0 ? '+' : ''}${pct.toFixed(1)}%` : ''}
                  </div>
                </div>
              )
            })}
          </div>
          <div className="flex items-center gap-4 mt-3 pt-3 border-t border-border text-[10px] text-muted">
            <span className="flex items-center gap-1.5"><span className="w-4 h-2.5 rounded bg-primary/70 inline-block" /> {curYear}</span>
            <span className="flex items-center gap-1.5"><span className="w-4 h-2.5 rounded bg-muted-foreground/40 inline-block" /> {curYear - 1}</span>
          </div>
        </div>
      )}
    </div>
  )
}

function MonthCalendar({ year, month, offerings, missingSundays, onSelectDate }: {
  year: number
  month: number
  offerings: ApprovedOffering[]
  missingSundays: string[]
  onSelectDate: (offeringId: number | null) => void
}) {
  // Build calendar grid
  const firstDay = new Date(year, month, 1)
  const lastDay = new Date(year, month + 1, 0)
  const startPad = firstDay.getDay() // 0=Sun
  const totalDays = lastDay.getDate()
  const today = new Date()

  // Map offering dates to their data
  const offeringByDate = new Map<string, ApprovedOffering>()
  for (const o of offerings) {
    const d = parseOfferingDate(o.offering_date)
    if (d) offeringByDate.set(d.toDateString(), o)
  }

  const missingSet = new Set(missingSundays.map(s => parseOfferingDate(s)?.toDateString()).filter(Boolean))

  const days: Array<{ day: number; date: Date; isSunday: boolean; offering: ApprovedOffering | null; isMissing: boolean; isToday: boolean; isFuture: boolean }> = []
  for (let d = 1; d <= totalDays; d++) {
    const date = new Date(year, month, d)
    const key = date.toDateString()
    days.push({
      day: d,
      date,
      isSunday: date.getDay() === 0,
      offering: offeringByDate.get(key) || null,
      isMissing: missingSet.has(key),
      isToday: key === today.toDateString(),
      isFuture: date > today,
    })
  }

  return (
    <div className="rounded-xl border border-border bg-card overflow-hidden">
      <div className="grid grid-cols-7 text-center text-[10px] text-muted font-medium border-b border-border bg-card">
        {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(d => (
          <div key={d} className={`py-1.5 ${d === 'Sun' ? 'text-primary font-bold' : ''}`}>{d}</div>
        ))}
      </div>
      <div className="grid grid-cols-7 text-center">
        {/* Padding for days before the 1st */}
        {Array.from({ length: startPad }).map((_, i) => (
          <div key={`pad-${i}`} className="py-2" />
        ))}
        {days.map(({ day, isSunday, offering, isMissing, isToday, isFuture }) => {
          const t = offering ? rowTotal(offering) : 0
          return (
            <div
              key={day}
              onClick={() => offering && onSelectDate(offering.id)}
              className={`py-1.5 px-0.5 text-xs transition-colors relative ${
                offering ? 'cursor-pointer hover:bg-primary/10' : ''
              } ${isToday ? 'ring-1 ring-primary ring-inset' : ''} ${
                isFuture ? 'opacity-30' : ''
              }`}
            >
              <div className={`${isSunday ? 'font-bold' : ''} ${
                offering ? 'text-success' : isMissing ? 'text-warning' : isSunday ? 'text-primary' : 'text-muted'
              }`}>
                {day}
              </div>
              {offering && (
                <div className="text-[8px] text-success font-medium truncate">
                  ${t.toFixed(0)}
                </div>
              )}
              {isMissing && (
                <div className="text-[8px] text-warning">missing</div>
              )}
              {isSunday && !offering && !isMissing && !isFuture && (
                <div className="w-1.5 h-1.5 rounded-full bg-primary/30 mx-auto mt-0.5" />
              )}
            </div>
          )
        })}
      </div>
      {/* Legend */}
      <div className="flex items-center justify-center gap-4 py-1.5 border-t border-border text-[9px] text-muted">
        <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-success" /> Has offering</span>
        <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-warning" /> Missing Sunday</span>
        <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-primary/30" /> Sunday (future)</span>
      </div>
    </div>
  )
}

export function ReportsPage() {
  const navigate = useNavigate()
  const now = new Date()
  const [viewMode, setViewMode] = useState<ViewMode>('monthly')
  const [month, setMonth] = useState(now.getMonth())
  const [year, setYear] = useState(now.getFullYear())
  const [dateFrom, setDateFrom] = useState('')
  const [dateTo, setDateTo] = useState('')
  const { data: defaultRecipients } = useQuery({
    queryKey: ['settings', 'report_recipients'],
    queryFn: async () => {
      const { data } = await supabase.from('app_settings').select('value').eq('key', 'report_recipients').single()
      return data?.value || ''
    },
  })

  const [expandedId, setExpandedId] = useState<number | null>(null)
  const [sortKey, setSortKey] = useState<SortKey>('offering_date')
  const [sortDir, setSortDir] = useState<SortDir>('asc')
  const [filterText, setFilterText] = useState('')

  const [emailSending, setEmailSending] = useState(false)
  const [emailTarget, setEmailTarget] = useState<{ type: string; offering?: ApprovedOffering } | null>(null)
  const [emailRecipients, setEmailRecipients] = useState('')
  const [showMissing, setShowMissing] = useState(true)
  const [displayMode, setDisplayMode] = useState<'table' | 'cards'>('table')

  const [selectedCats, setSelectedCats] = useState<Set<Category>>(() => {
    try {
      const saved = localStorage.getItem('ots:report_categories')
      if (saved) {
        const parsed = JSON.parse(saved) as Category[]
        if (Array.isArray(parsed) && parsed.length > 0) return new Set(parsed)
      }
    } catch { /* ignore */ }
    return new Set<Category>(['general', 'cash', 'sunday_school', 'building_fund', 'misc'])
  })
  type DriveStatus = null | 'uploading' | { name: string; link: string } | { error: string }
  const [driveStatus, setDriveStatus] = useState<DriveStatus>(null)
  const [cardsExporting, setCardsExporting] = useState(false)
  const [cardDriveStatus, setCardDriveStatus] = useState<Record<number, DriveStatus>>({})

  const toggleCat = (cat: Category) => {
    setSelectedCats(prev => {
      if (prev.size === 1 && prev.has(cat)) return prev // keep at least one selected
      const next = new Set(prev)
      if (next.has(cat)) next.delete(cat)
      else next.add(cat)
      localStorage.setItem('ots:report_categories', JSON.stringify([...next]))
      return next
    })
  }

  const { data: churchName } = useQuery({
    queryKey: ['settings', 'church_name'],
    queryFn: async () => {
      const { data } = await supabase.from('app_settings').select('value').eq('key', 'church_name').single()
      return data?.value || 'Offering Report'
    },
  })

  const accentColors = useAccentColors()

  const { data: allApproved, isLoading } = useQuery({
    queryKey: ['offerings', 'approved'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('offerings')
        .select('id, filename, offering_date, general, cash, sunday_school, building_fund, misc, notes, approved_by_email, locked_at')
        .eq('status', 'approved')
      if (error) throw error
      return data as ApprovedOffering[]
    },
  })

  const offerings = useMemo(() => {
    let filtered = (allApproved || []).filter(o => {
      const d = parseOfferingDate(o.offering_date)
      if (!d) return false
      if (viewMode === 'monthly') {
        return d.getMonth() === month && d.getFullYear() === year
      } else if (viewMode === 'yearly') {
        return d.getFullYear() === year
      } else {
        const from = dateFrom ? new Date(dateFrom) : null
        const to = dateTo ? new Date(dateTo + 'T23:59:59') : null
        if (from && d < from) return false
        if (to && d > to) return false
        return true
      }
    })

    if (filterText) {
      const q = filterText.toLowerCase()
      filtered = filtered.filter(o =>
        (o.offering_date || '').toLowerCase().includes(q) ||
        (o.filename || '').toLowerCase().includes(q) ||
        (o.notes || '').toLowerCase().includes(q) ||
        rowTotal(o).toFixed(2).includes(q)
      )
    }

    filtered.sort((a, b) => {
      let va: number, vb: number
      if (sortKey === 'offering_date') {
        va = parseOfferingDate(a.offering_date)?.getTime() || 0
        vb = parseOfferingDate(b.offering_date)?.getTime() || 0
      } else if (sortKey === 'total') {
        va = rowTotal(a); vb = rowTotal(b)
      } else {
        va = (a[sortKey] as number) || 0; vb = (b[sortKey] as number) || 0
      }
      return sortDir === 'asc' ? va - vb : vb - va
    })
    return filtered
  }, [allApproved, month, year, dateFrom, dateTo, viewMode, sortKey, sortDir, filterText])

  const toggleSort = (key: SortKey) => {
    if (sortKey === key) setSortDir(d => d === 'asc' ? 'desc' : 'asc')
    else { setSortKey(key); setSortDir(key === 'offering_date' ? 'asc' : 'desc') }
  }

  const prevMonth = () => { if (month === 0) { setMonth(11); setYear(y => y - 1) } else setMonth(m => m - 1) }
  const nextMonth = () => { if (month === 11) { setMonth(0); setYear(y => y + 1) } else setMonth(m => m + 1) }

  // Find missing Sundays (monthly and yearly views, only past dates)
  const missingSundays = useMemo(() => {
    if (viewMode === 'range') return []
    const sundays: string[] = []
    const today = new Date()
    today.setHours(23, 59, 59)
    const startMonth = viewMode === 'yearly' ? 0 : month
    const endMonth = viewMode === 'yearly' ? 11 : month
    const d = new Date(year, startMonth, 1)
    const endDate = new Date(year, endMonth + 1, 0)
    while (d <= endDate) {
      if (d.getDay() === 0 && d <= today) {
        const mm = String(d.getMonth() + 1).padStart(2, '0')
        const dd = String(d.getDate()).padStart(2, '0')
        sundays.push(`${mm}/${dd}/${d.getFullYear()}`)
      }
      d.setDate(d.getDate() + 1)
    }
    // Compare by parsed date (not string) to handle format differences
    const offeringTimestamps = new Set(
      offerings.map(o => parseOfferingDate(o.offering_date)?.toDateString()).filter(Boolean)
    )
    return sundays.filter(s => {
      const parsed = parseOfferingDate(s)
      return parsed && !offeringTimestamps.has(parsed.toDateString())
    })
  }, [offerings, month, year, viewMode])

  // Merge offerings and missing Sundays for display
  type DisplayRow = { type: 'offering'; data: ApprovedOffering } | { type: 'missing'; date: string }
  const displayRows = useMemo((): DisplayRow[] => {
    const rows: DisplayRow[] = offerings.map(o => ({ type: 'offering' as const, data: o }))
    if (showMissing) {
      for (const date of missingSundays) {
        rows.push({ type: 'missing' as const, date })
      }
    }
    rows.sort((a, b) => {
      const dateA = a.type === 'offering' ? a.data.offering_date : a.date
      const dateB = b.type === 'offering' ? b.data.offering_date : b.date
      const da = parseOfferingDate(dateA || '')?.getTime() || 0
      const db = parseOfferingDate(dateB || '')?.getTime() || 0
      return da - db
    })
    return rows
  }, [offerings, missingSundays, showMissing])

  const grandTotal = offerings.reduce((acc, o) => ({
    general: acc.general + (o.general || 0), cash: acc.cash + (o.cash || 0),
    sunday_school: acc.sunday_school + (o.sunday_school || 0),
    building_fund: acc.building_fund + (o.building_fund || 0), misc: acc.misc + (o.misc || 0),
  }), { general: 0, cash: 0, sunday_school: 0, building_fund: 0, misc: 0 })

  const grandTotalSum = grandTotal.general + grandTotal.cash + grandTotal.sunday_school +
    grandTotal.building_fund + grandTotal.misc

  // Derived export values — respect selectedCats (display always shows all)
  const catList = ALL_CATS.filter(c => selectedCats.has(c.key))
  const filteredRowTotal = (o: ApprovedOffering) =>
    catList.reduce((sum, c) => sum + ((o as any)[c.key] || 0), 0)
  const filteredGrandTotal = catList.reduce((acc, c) => ({
    ...acc, [c.key]: offerings.reduce((sum, o) => sum + ((o as any)[c.key] || 0), 0),
  }), {} as Record<string, number>)
  const filteredGrandTotalSum = catList.reduce((sum, c) => sum + (filteredGrandTotal[c.key] || 0), 0)

  // Reset drive status when period changes
  useEffect(() => { setDriveStatus(null) }, [viewMode, month, year, dateFrom, dateTo])

  const periodLabel = viewMode === 'monthly'
    ? `${MONTHS[month]} ${year}`
    : viewMode === 'yearly'
    ? `${year}`
    : `${dateFrom || 'Start'} to ${dateTo || 'End'}`

  const title = churchName || 'Offering Report'

  // Export functions
  const printReport = async () => {
    const today = new Date().toISOString().split('T')[0]
    try {
      await generateAndDownloadPdf({
        title,
        subtitle: periodLabel,
        headers: ['Date', ...catList.map(c => c.label), 'Total'],
        rows: offerings.map(o => [
          formatDate(o.offering_date),
          ...catList.map(c => fmt((o as any)[c.key])),
          '$' + filteredRowTotal(o).toFixed(2),
        ]),
        footer_row: [
          'Total',
          ...catList.map(c => '$' + (filteredGrandTotal[c.key] || 0).toFixed(2)),
          '$' + filteredGrandTotalSum.toFixed(2),
        ],
        accent_color: accentColors.report || '#16a34a',
        filename: 'ots_report_' + periodLabel.replace(/\s+/g, '_').toLowerCase() + '_' + today + '.pdf',
      })
    } catch (err) { alert(err instanceof Error ? err.message : 'PDF failed') }
  }

  const handleDriveUpload = async () => {
    setDriveStatus('uploading')
    try {
      const today = new Date().toISOString().split('T')[0]
      const data = await generateAndUploadPdf({
        title,
        subtitle: periodLabel,
        headers: ['Date', ...catList.map(c => c.label), 'Total'],
        rows: offerings.map(o => [
          formatDate(o.offering_date),
          ...catList.map(c => fmt((o as any)[c.key])),
          '$' + filteredRowTotal(o).toFixed(2),
        ]),
        footer_row: [
          'Total',
          ...catList.map(c => '$' + (filteredGrandTotal[c.key] || 0).toFixed(2)),
          '$' + filteredGrandTotalSum.toFixed(2),
        ],
        accent_color: accentColors.report || '#16a34a',
        filename: 'OTS_Report_' + periodLabel.replace(/\s+/g, '_') + '_' + today + '.pdf',
      })
      if (data.drive) setDriveStatus({ name: data.drive.name, link: data.drive.link })
      else setDriveStatus({ error: data.drive_error || 'Drive not configured' })
    } catch (err) {
      setDriveStatus({ error: err instanceof Error ? err.message : 'Upload failed' })
    }
  }

  const exportCardsAsPdf = async (singleOffering?: ApprovedOffering) => {
    setCardsExporting(true)
    try {
      const targets = singleOffering ? [singleOffering] : offerings
      const cards = targets.map(o => ({
        date: formatDate(o.offering_date),
        rows: catList
          .filter(c => (o as any)[c.key] > 0)
          .map(c => [c.label, '$' + (o as any)[c.key].toFixed(2)]),
        total: '$' + filteredRowTotal(o).toFixed(2),
      }))
      const resp = await fetch((await getBackendUrl()) + '/api/pdf/generate-cards', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title,
          period: singleOffering
            ? 'Week of ' + formatDate(singleOffering.offering_date)
            : periodLabel,
          cards,
          accent_color: accentColors.card || accentColors.report || '#16a34a',
        }),
      })
      const data = await resp.json()
      if (!data.success) throw new Error(data.detail || 'Failed')
      const blob = new Blob([Uint8Array.from(atob(data.pdf_base64), c => c.charCodeAt(0))], { type: 'application/pdf' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url; a.download = data.filename; a.click()
      URL.revokeObjectURL(url)
    } catch (err) {
      alert(err instanceof Error ? err.message : 'Cards PDF failed')
    } finally {
      setCardsExporting(false)
    }
  }

  const uploadCardToDrive = async (o: ApprovedOffering) => {
    setCardDriveStatus(prev => ({ ...prev, [o.id]: 'uploading' }))
    try {
      const resp = await fetch((await getBackendUrl()) + '/api/pdf/generate-cards', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title,
          period: 'Week of ' + formatDate(o.offering_date),
          cards: [{
            date: formatDate(o.offering_date),
            rows: catList.filter(c => (o as any)[c.key] > 0).map(c => [c.label, '$' + (o as any)[c.key].toFixed(2)]),
            total: '$' + filteredRowTotal(o).toFixed(2),
          }],
          accent_color: accentColors.card || accentColors.report || '#16a34a',
          upload_to_drive: true,
        }),
      })
      const data = await resp.json()
      if (!data.success) throw new Error(data.detail || 'Failed')
      if (data.drive) {
        setCardDriveStatus(prev => ({ ...prev, [o.id]: { name: data.drive.name, link: data.drive.link } }))
      } else {
        setCardDriveStatus(prev => ({ ...prev, [o.id]: { error: data.drive_error || 'Drive not configured' } }))
      }
    } catch (err) {
      setCardDriveStatus(prev => ({ ...prev, [o.id]: { error: err instanceof Error ? err.message : 'Upload failed' } }))
    }
  }

  // Initialize email recipients from defaults when target changes
  useEffect(() => {
    if (emailTarget && defaultRecipients && !emailRecipients) {
      setEmailRecipients(defaultRecipients)
    }
  }, [emailTarget, defaultRecipients])

  const sendEmail = async (subject: string, htmlBody: string) => {
    if (!emailRecipients.trim()) return
    setEmailSending(true)
    try {
      const resp = await fetch((await getBackendUrl()) + '/api/email/send', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          to: emailRecipients.split(',').map((e: string) => e.trim()).filter(Boolean),
          subject,
          html_body: htmlBody,
        }),
      })
      const data = await resp.json()
      if (data.success) { setEmailTarget(null); setEmailRecipients('') }
      else alert(data.detail || data.error || 'Send failed')
    } catch (err) { alert(err instanceof Error ? err.message : 'Failed') }
    finally { setEmailSending(false) }
  }

  const buildEmailReportHtml = () => {
    const rc = accentColors.report || '#16a34a'
    const numCols = catList.length + 2
    const datePct = 20
    const otherPct = Math.floor((100 - datePct) / (numCols - 1))
    const thStyle = 'padding:10px 12px;text-align:right;font-size:11px;text-transform:uppercase;color:#64748b;border-bottom:2px solid #cbd5e1'
    const tdStyle = 'padding:8px 12px;text-align:right;border-bottom:1px solid #e5e7eb'
    const ftStyle = 'padding:10px 12px;text-align:right;font-weight:bold'
    const rows = offerings.map((o, i) => {
      const bg = i % 2 === 0 ? '#ffffff' : '#f8fafc'
      return '<tr style="background:' + bg + '"><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">' + formatDate(o.offering_date) + '</td>' +
        catList.map(c => '<td style="' + tdStyle + '">' + fmt((o as any)[c.key]) + '</td>').join('') +
        '<td style="' + tdStyle + ';font-weight:bold">$' + filteredRowTotal(o).toFixed(2) + '</td></tr>'
    }).join('')
    const colgroup = '<colgroup><col style="width:' + datePct + '%"/>' +
      catList.map(() => '<col style="width:' + otherPct + '%"/>').join('') +
      '<col style="width:' + otherPct + '%"/></colgroup>'
    const headerCells = '<th style="' + thStyle + ';text-align:left">Date</th>' +
      catList.map(c => '<th style="' + thStyle + '">' + c.label + '</th>').join('') +
      '<th style="' + thStyle + '">Total</th>'
    const footerCells = '<td style="' + ftStyle + ';text-align:left">Total</td>' +
      catList.map(c => '<td style="' + ftStyle + '">$' + (filteredGrandTotal[c.key] || 0).toFixed(2) + '</td>').join('') +
      '<td style="' + ftStyle + '">$' + filteredGrandTotalSum.toFixed(2) + '</td>'
    return '<div style="font-family:system-ui,sans-serif;max-width:700px;margin:0 auto;color:#1a1a2e">' +
      '<div style="background:' + rc + ';color:white;padding:20px 24px;border-radius:8px 8px 0 0">' +
        '<h1 style="margin:0;font-size:18px">' + title + '</h1>' +
        '<p style="margin:4px 0 0;font-size:13px;opacity:0.85">' + periodLabel + '</p>' +
      '</div>' +
      '<div style="border:1px solid #e5e7eb;border-top:none;border-radius:0 0 8px 8px;overflow:hidden">' +
      '<table style="width:100%;border-collapse:collapse;font-size:13px;table-layout:fixed">' +
      colgroup +
      '<thead><tr style="background:#f1f5f9">' + headerCells + '</tr></thead>' +
      '<tbody>' + rows + '</tbody>' +
      '<tfoot><tr style="background:' + rc + ';color:white">' + footerCells + '</tr></tfoot>' +
      '</table></div>' +
      '<p style="margin-top:16px;font-size:10px;color:#94a3b8;text-align:center">Generated by OTS</p></div>'
  }

  const exportCsv = () => {
    const hdrs = 'Date,' + catList.map(c => c.label).join(',') + ',Total\n'
    const rows = offerings.map(o =>
      `${o.offering_date || ''},${catList.map(c => (o as any)[c.key]).join(',')},${filteredRowTotal(o)}`
    ).join('\n')
    const totalsRow = `Total,${catList.map(c => filteredGrandTotal[c.key] || 0).join(',')},${filteredGrandTotalSum}`
    const blob = new Blob([hdrs + rows + '\n' + totalsRow], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `offerings_${periodLabel.replace(/\s+/g, '_').toLowerCase()}.csv`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Reports</h1>
          <p className="text-muted text-sm">{title} — {viewMode === 'monthly' ? 'Monthly' : viewMode === 'yearly' ? 'Yearly' : viewMode === 'trends' ? 'Trends' : 'Date Range'} Report</p>
        </div>
      </div>

      {/* View mode toggle + date controls */}
      <div className="flex items-center gap-4 flex-wrap">
        <div className="flex gap-1 bg-card border border-border rounded-lg p-0.5">
          <button onClick={() => setViewMode('monthly')}
            className={`px-3 py-1.5 text-xs font-medium rounded-md cursor-pointer transition-colors ${
              viewMode === 'monthly' ? 'bg-primary text-primary-foreground' : 'text-muted hover:text-foreground'
            }`}>Monthly</button>
          <button onClick={() => setViewMode('yearly')}
            className={`px-3 py-1.5 text-xs font-medium rounded-md cursor-pointer transition-colors ${
              viewMode === 'yearly' ? 'bg-primary text-primary-foreground' : 'text-muted hover:text-foreground'
            }`}>Yearly</button>
          <button onClick={() => setViewMode('range')}
            className={`px-3 py-1.5 text-xs font-medium rounded-md cursor-pointer transition-colors flex items-center gap-1 ${
              viewMode === 'range' ? 'bg-primary text-primary-foreground' : 'text-muted hover:text-foreground'
            }`}><CalendarRange className="w-3 h-3" /> Range</button>
          <button onClick={() => setViewMode('trends')}
            className={`px-3 py-1.5 text-xs font-medium rounded-md cursor-pointer transition-colors flex items-center gap-1 ${
              viewMode === 'trends' ? 'bg-primary text-primary-foreground' : 'text-muted hover:text-foreground'
            }`}><TrendingUp className="w-3 h-3" /> Trends</button>
        </div>

        {viewMode === 'monthly' ? (
          <div className="flex items-center gap-3">
            <button onClick={prevMonth} className="p-1.5 rounded-lg border border-border hover:bg-muted-foreground/10 cursor-pointer">
              <ChevronLeft className="w-4 h-4" />
            </button>
            <div className="text-center min-w-[150px]">
              <p className="text-sm font-bold">{MONTHS[month]} {year}</p>
            </div>
            <button onClick={nextMonth} className="p-1.5 rounded-lg border border-border hover:bg-muted-foreground/10 cursor-pointer">
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        ) : viewMode === 'yearly' ? (
          <div className="flex items-center gap-3">
            <button onClick={() => setYear(y => y - 1)} className="p-1.5 rounded-lg border border-border hover:bg-muted-foreground/10 cursor-pointer">
              <ChevronLeft className="w-4 h-4" />
            </button>
            <div className="text-center min-w-[80px]">
              <p className="text-sm font-bold">{year}</p>
            </div>
            <button onClick={() => setYear(y => y + 1)} className="p-1.5 rounded-lg border border-border hover:bg-muted-foreground/10 cursor-pointer">
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        ) : viewMode === 'range' ? (
          <div className="flex items-center gap-2">
            <input type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)}
              className="px-3 py-1.5 text-sm rounded-lg border border-border bg-background" />
            <span className="text-xs text-muted">to</span>
            <input type="date" value={dateTo} onChange={e => setDateTo(e.target.value)}
              className="px-3 py-1.5 text-sm rounded-lg border border-border bg-background" />
          </div>
        ) : null}

        {viewMode !== 'trends' && (
          <span className="text-xs text-muted">
            {offerings.length} offering{offerings.length !== 1 ? 's' : ''}
            {missingSundays.length > 0 && (
              <button onClick={() => setShowMissing(!showMissing)}
                className={`ml-2 cursor-pointer ${showMissing ? 'text-warning' : 'text-muted line-through'}`}>
                {missingSundays.length} missing {showMissing ? '(hide)' : '(show)'}
              </button>
            )}
          </span>
        )}
      </div>

      {/* Month calendar view (monthly mode only) */}
      {viewMode === 'monthly' && !isLoading && (
        <MonthCalendar
          year={year}
          month={month}
          offerings={offerings}
          missingSundays={missingSundays}
          onSelectDate={(offeringId) => {
            if (offeringId) setExpandedId(expandedId === offeringId ? null : offeringId)
          }}
        />
      )}

      {viewMode === 'trends' ? (
        <TrendsTab allApproved={allApproved || []} />
      ) : isLoading ? (
        <div className="flex justify-center py-10"><Loader2 className="w-6 h-6 animate-spin text-primary" /></div>
      ) : offerings.length > 0 ? (
        <>
          {/* Summary cards */}
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
            {[
              { label: 'General', value: grandTotal.general, color: 'text-blue-500' },
              { label: 'Cash', value: grandTotal.cash, color: 'text-green-500' },
              { label: 'Sunday School', value: grandTotal.sunday_school, color: 'text-purple-500' },
              { label: 'Building Fund', value: grandTotal.building_fund, color: 'text-orange-500' },
              { label: 'Miscellaneous', value: grandTotal.misc, color: 'text-muted' },
              { label: 'Total', value: grandTotalSum, color: 'text-primary' },
            ].map(({ label, value, color }) => (
              <div key={label} className="rounded-lg border border-border bg-card p-3 text-center">
                <p className="text-[10px] text-muted uppercase tracking-wider">{label}</p>
                <p className={`text-lg font-bold ${color}`}>${value.toFixed(2)}</p>
              </div>
            ))}
          </div>

          {/* Year-to-date summary */}
          {(() => {
            const currentYear = viewMode === 'monthly' ? year : new Date().getFullYear()
            const ytdOfferings = (allApproved || []).filter(o => {
              const d = parseOfferingDate(o.offering_date)
              return d && d.getFullYear() === currentYear
            })
            const ytd = ytdOfferings.reduce((acc, o) => ({
              general: acc.general + (o.general || 0), cash: acc.cash + (o.cash || 0),
              sunday_school: acc.sunday_school + (o.sunday_school || 0),
              building_fund: acc.building_fund + (o.building_fund || 0), misc: acc.misc + (o.misc || 0),
            }), { general: 0, cash: 0, sunday_school: 0, building_fund: 0, misc: 0 })
            const ytdTotal = ytd.general + ytd.cash + ytd.sunday_school + ytd.building_fund + ytd.misc

            return ytdTotal > 0 ? (
              <div className="rounded-lg border border-border/50 bg-card/50 px-4 py-2.5 flex items-center justify-between">
                <span className="text-xs text-muted">Year-to-Date ({currentYear}): {ytdOfferings.length} offerings</span>
                <div className="flex items-center gap-4 text-xs">
                  <span>General: <strong>${ytd.general.toFixed(0)}</strong></span>
                  <span>Cash: <strong>${ytd.cash.toFixed(0)}</strong></span>
                  <span>SS: <strong>${ytd.sunday_school.toFixed(0)}</strong></span>
                  <span>BF: <strong>${ytd.building_fund.toFixed(0)}</strong></span>
                  {ytd.misc > 0 && <span>Misc: <strong>${ytd.misc.toFixed(0)}</strong></span>}
                  <span className="text-primary font-bold">Total: ${ytdTotal.toFixed(2)}</span>
                </div>
              </div>
            ) : null
          })()}

          {/* Category selector — persisted, affects all exports */}
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-xs text-muted">Export:</span>
            {ALL_CATS.map(c => (
              <button key={c.key} onClick={() => toggleCat(c.key)}
                className={`px-2.5 py-1 text-xs rounded-full border transition-colors cursor-pointer ${
                  selectedCats.has(c.key)
                    ? 'bg-primary/10 border-primary/40 text-primary font-medium'
                    : 'border-border text-muted hover:text-foreground'
                }`}>
                {c.label}
              </button>
            ))}
            {selectedCats.size < 5 && (
              <button onClick={() => {
                const all = new Set<Category>(['general', 'cash', 'sunday_school', 'building_fund', 'misc'])
                setSelectedCats(all)
                localStorage.setItem('ots:report_categories', JSON.stringify([...all]))
              }} className="text-[10px] text-muted hover:text-foreground cursor-pointer underline">
                All
              </button>
            )}
          </div>

          {/* Filter + Export bar */}
          <div className="flex items-center justify-between gap-3 flex-wrap">
            <div className="relative flex-1 max-w-xs">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted" />
              <input type="text" placeholder="Filter..."
                value={filterText} onChange={e => setFilterText(e.target.value)}
                className="w-full pl-9 pr-3 py-1.5 text-sm rounded-lg border border-border bg-background" />
            </div>
            <div className="flex gap-2 flex-wrap">
              <button onClick={printReport}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 cursor-pointer">
                <Printer className="w-3.5 h-3.5" /> PDF
              </button>
              <button onClick={() => setDisplayMode(displayMode === 'cards' ? 'table' : 'cards')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm cursor-pointer ${
                  displayMode === 'cards' ? 'bg-primary text-primary-foreground' : 'border border-border hover:bg-muted-foreground/10'
                }`}>
                <Share2 className="w-3.5 h-3.5" /> {displayMode === 'cards' ? 'Table' : 'Cards'}
              </button>
              <button onClick={exportCsv}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border hover:bg-muted-foreground/10 text-sm cursor-pointer">
                <Download className="w-3.5 h-3.5" /> CSV
              </button>
              <button onClick={() => exportCardsAsPdf()} disabled={cardsExporting}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border hover:bg-muted-foreground/10 text-sm cursor-pointer disabled:opacity-60">
                {cardsExporting ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Share2 className="w-3.5 h-3.5" />}
                Cards PDF
              </button>
              <div className="flex items-center gap-1.5">
                <button onClick={handleDriveUpload} disabled={driveStatus === 'uploading'}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border hover:bg-muted-foreground/10 text-sm cursor-pointer disabled:opacity-60">
                  {driveStatus === 'uploading'
                    ? <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Uploading...</>
                    : <><CloudUpload className="w-3.5 h-3.5" /> Drive</>}
                </button>
                {driveStatus && driveStatus !== 'uploading' && (
                  'name' in driveStatus
                    ? <a href={(driveStatus as { name: string; link: string }).link} target="_blank" rel="noreferrer"
                        className="flex items-center gap-0.5 text-xs text-success hover:underline">
                        <ExternalLink className="w-3 h-3" />
                        {(driveStatus as { name: string; link: string }).name}
                      </a>
                    : <span className="text-xs text-destructive">{(driveStatus as { error: string }).error}</span>
                )}
              </div>
              <button onClick={() => setEmailTarget(emailTarget?.type === 'report' ? null : { type: 'report' })}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm cursor-pointer ${
                  emailTarget?.type === 'report' ? 'bg-primary text-primary-foreground' : 'border border-border hover:bg-muted-foreground/10'
                }`}>
                <Mail className="w-3.5 h-3.5" /> Email
              </button>
            </div>
          </div>

          {/* Inline email panel */}
          {emailTarget && (
            <div className="rounded-xl border border-primary/30 bg-primary/5 p-4">
              <div className="flex items-center gap-3">
                <Mail className="w-4 h-4 text-primary flex-shrink-0" />
                <input type="text" placeholder="Recipients (comma-separated emails)"
                  value={emailRecipients}
                  onChange={e => setEmailRecipients(e.target.value)}
                  className="flex-1 px-3 py-1.5 text-sm rounded-lg border border-border bg-background" />
                <button disabled={emailSending || !emailRecipients.trim()}
                  onClick={() => {
                    const o = emailTarget.offering
                    if (emailTarget.type === 'report') {
                      sendEmail(title + ' — ' + periodLabel, buildEmailReportHtml())
                    } else if (o) {
                      sendEmail(title + ' — Week of ' + formatDate(o.offering_date), buildEmailCard(title, o, catList, accentColors.card))
                    }
                  }}
                  className="flex items-center gap-1.5 px-4 py-1.5 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 cursor-pointer disabled:opacity-50">
                  {emailSending ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Mail className="w-3.5 h-3.5" />}
                  Send
                </button>
                <button onClick={() => { setEmailTarget(null); setEmailRecipients('') }}
                  className="text-xs text-muted hover:text-foreground cursor-pointer">Cancel</button>
              </div>
              <p className="text-[10px] text-muted mt-1.5 ml-8">
                {emailTarget.type === 'report' ? 'Sending full report table' : 'Sending weekly offering card for ' + formatDate(emailTarget.offering?.offering_date || '')}
              </p>
            </div>
          )}

          {/* Cards view (inline) */}
          {displayMode === 'cards' && (
            <div>
              {/* Period summary card */}
              <div className="rounded-xl border border-primary/30 bg-primary/5 p-5 mb-4">
                <h2 className="text-lg font-bold text-primary">{title}</h2>
                <p className="text-sm text-muted">{periodLabel} — {offerings.length} offering{offerings.length !== 1 ? 's' : ''}</p>
                <div className="flex gap-6 mt-3 text-sm">
                  <span>General: <strong>${grandTotal.general.toFixed(2)}</strong></span>
                  <span>Cash: <strong>${grandTotal.cash.toFixed(2)}</strong></span>
                  {grandTotal.sunday_school > 0 && <span>SS: <strong>${grandTotal.sunday_school.toFixed(2)}</strong></span>}
                  {grandTotal.building_fund > 0 && <span>BF: <strong>${grandTotal.building_fund.toFixed(2)}</strong></span>}
                  {grandTotal.misc > 0 && <span>Misc: <strong>${grandTotal.misc.toFixed(2)}</strong></span>}
                  <span className="text-primary font-bold">Total: ${grandTotalSum.toFixed(2)}</span>
                </div>
              </div>

              {/* Individual week cards */}
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                {offerings.map(o => {
                  const t = rowTotal(o)
                  return (
                    <div key={o.id} className="rounded-xl border border-border overflow-hidden hover:border-primary/30 transition-colors">
                      <div className="bg-card px-4 py-3 border-b border-border">
                        <p className="text-sm font-bold">{formatDate(o.offering_date)}</p>
                        <p className="text-[10px] text-muted">Week offering</p>
                      </div>
                      <div className="px-4 py-3 space-y-1.5">
                        {o.general > 0 && (
                          <div className="flex justify-between text-sm">
                            <span className="text-muted">General (Checks)</span>
                            <span>${o.general.toFixed(2)}</span>
                          </div>
                        )}
                        {o.cash > 0 && (
                          <div className="flex justify-between text-sm">
                            <span className="text-muted">Cash</span>
                            <span>${o.cash.toFixed(2)}</span>
                          </div>
                        )}
                        {o.sunday_school > 0 && (
                          <div className="flex justify-between text-sm">
                            <span className="text-muted">Sunday School</span>
                            <span>${o.sunday_school.toFixed(2)}</span>
                          </div>
                        )}
                        {o.building_fund > 0 && (
                          <div className="flex justify-between text-sm">
                            <span className="text-muted">Building Fund</span>
                            <span>${o.building_fund.toFixed(2)}</span>
                          </div>
                        )}
                        {o.misc > 0 && (
                          <div className="flex justify-between text-sm">
                            <span className="text-muted">Miscellaneous</span>
                            <span>${o.misc.toFixed(2)}</span>
                          </div>
                        )}
                        <div className="flex justify-between text-sm font-bold pt-1.5 border-t border-border">
                          <span>Total</span>
                          <span className="text-primary">${t.toFixed(2)}</span>
                        </div>
                      </div>
                      <div className="px-4 py-2 border-t border-border flex flex-col gap-1.5">
                        <div className="flex gap-2">
                          <button onClick={() => navigate(`/review?id=${o.id}`)}
                            className="flex items-center gap-1 px-2 py-1 text-[10px] rounded border border-border hover:bg-muted-foreground/10 cursor-pointer">
                            <ExternalLink className="w-3 h-3" /> Review
                          </button>
                          <button onClick={() => exportCardsAsPdf(o)} disabled={cardsExporting}
                            className="flex items-center gap-1 px-2 py-1 text-[10px] rounded border border-border hover:bg-muted-foreground/10 cursor-pointer disabled:opacity-50">
                            <Download className="w-3 h-3" /> PDF
                          </button>
                          <button onClick={() => uploadCardToDrive(o)} disabled={cardDriveStatus[o.id] === 'uploading'}
                            className="flex items-center gap-1 px-2 py-1 text-[10px] rounded border border-border hover:bg-muted-foreground/10 cursor-pointer disabled:opacity-50">
                            {cardDriveStatus[o.id] === 'uploading'
                              ? <Loader2 className="w-3 h-3 animate-spin" />
                              : <CloudUpload className="w-3 h-3" />}
                            Drive
                          </button>
                          <button onClick={() => setEmailTarget(emailTarget?.offering?.id === o.id ? null : { type: 'card', offering: o })}
                            className="flex items-center gap-1 px-2 py-1 text-[10px] rounded border border-border hover:bg-muted-foreground/10 cursor-pointer">
                            <Mail className="w-3 h-3" /> Email
                          </button>
                        </div>
                        {cardDriveStatus[o.id] && cardDriveStatus[o.id] !== 'uploading' && (
                          'name' in (cardDriveStatus[o.id] as object)
                            ? <a href={(cardDriveStatus[o.id] as { name: string; link: string }).link}
                                target="_blank" rel="noreferrer"
                                className="flex items-center gap-1 text-[10px] text-success hover:underline">
                                <ExternalLink className="w-2.5 h-2.5" />
                                {(cardDriveStatus[o.id] as { name: string; link: string }).name}
                              </a>
                            : <span className="text-[10px] text-destructive">
                                {(cardDriveStatus[o.id] as { error: string }).error}
                              </span>
                        )}
                      </div>
                    </div>
                  )
                })}
              </div>

              {/* Missing Sundays */}
              {showMissing && missingSundays.length > 0 && (
                <div className="mt-4 space-y-2">
                  {missingSundays.map(date => (
                    <div key={date} className="flex items-center gap-2 px-4 py-2 rounded-lg bg-warning/5 border border-warning/20">
                      <span className="w-3 h-3 rounded-full bg-warning/30" />
                      <span className="text-sm text-warning">{date} — No offering recorded</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* Sortable data table */}
          {displayMode === 'table' && <div className="rounded-xl border border-border overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-sm table-fixed">
                <colgroup>
                  <col className="w-[130px]" /> {/* Date */}
                  <col /> {/* General */}
                  <col /> {/* Cash */}
                  <col /> {/* Sunday School */}
                  <col /> {/* Building Fund */}
                  <col /> {/* Miscellaneous */}
                  <col /> {/* Total */}
                </colgroup>
                <thead>
                  <tr className="bg-card border-b border-border">
                    {COLUMNS.map(col => (
                      <th key={col.key} onClick={() => toggleSort(col.key)}
                        className={`px-3 py-3 text-xs font-medium text-muted cursor-pointer hover:text-foreground select-none transition-colors ${
                          col.key === 'offering_date' ? 'text-left' : 'text-right'
                        }`}>
                        <span className="inline-flex items-center gap-1">
                          {col.label}
                          {sortKey === col.key ? (
                            sortDir === 'asc' ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />
                          ) : (
                            <ArrowUpDown className="w-3 h-3 opacity-30" />
                          )}
                        </span>
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {displayRows.map((row) => {
                    if (row.type === 'missing') {
                      return (
                        <tr key={`missing-${row.date}`} className="bg-warning/5">
                          <td className="px-3 py-2 font-medium text-warning">
                            <div className="flex items-center gap-1.5">
                              <span className="w-3 h-3 rounded-full bg-warning/30 flex-shrink-0" />
                              {row.date}
                            </div>
                          </td>
                          <td colSpan={6} className="px-3 py-2 text-xs text-warning italic">
                            No offering recorded for this Sunday
                          </td>
                        </tr>
                      )
                    }
                    const o = row.data
                    return (
                      <React.Fragment key={o.id}>
                        <tr onClick={() => setExpandedId(expandedId === o.id ? null : o.id)}
                          className="hover:bg-muted-foreground/5 cursor-pointer">
                          <td className="px-3 py-2.5 font-medium">
                            <div className="flex items-center gap-1.5">
                              {expandedId === o.id ? <ChevronUp className="w-3 h-3 text-muted" /> : <ChevronDown className="w-3 h-3 text-muted" />}
                              {formatDate(o.offering_date)}
                            </div>
                          </td>
                          <td className="px-3 py-2.5 text-right">{fmt(o.general)}</td>
                          <td className="px-3 py-2.5 text-right">{fmt(o.cash)}</td>
                          <td className="px-3 py-2.5 text-right">{fmt(o.sunday_school)}</td>
                          <td className="px-3 py-2.5 text-right">{fmt(o.building_fund)}</td>
                          <td className="px-3 py-2.5 text-right">{fmt(o.misc)}</td>
                          <td className="px-3 py-2.5 text-right font-bold">${rowTotal(o).toFixed(2)}</td>
                        </tr>
                        {expandedId === o.id && (
                          <tr>
                            <td colSpan={7} className="px-4 py-3 bg-card/50">
                              <div className="flex items-start justify-between gap-4">
                                <div className="space-y-1 text-xs">
                                  <p className="font-medium text-sm mb-2">Week of {formatDate(o.offering_date)}</p>
                                  {o.general > 0 && <p>General (Checks): <strong>${o.general.toFixed(2)}</strong></p>}
                                  {o.cash > 0 && <p>Cash (Denominations): <strong>${o.cash.toFixed(2)}</strong></p>}
                                  {o.sunday_school > 0 && <p>Sunday School: <strong>${o.sunday_school.toFixed(2)}</strong></p>}
                                  {o.building_fund > 0 && <p>Building Fund: <strong>${o.building_fund.toFixed(2)}</strong></p>}
                                  {o.misc > 0 && <p>Miscellaneous: <strong>${o.misc.toFixed(2)}</strong></p>}
                                  <p className="pt-1 font-bold">Total: ${rowTotal(o).toFixed(2)}</p>
                                  {o.notes && <p className="text-muted pt-1">{o.notes}</p>}
                                </div>
                                <div className="flex gap-2 flex-shrink-0">
                                  <button onClick={e => { e.stopPropagation(); navigate(`/review?id=${o.id}`) }}
                                    className="flex items-center gap-1 px-2 py-1 text-xs rounded border border-border hover:bg-muted-foreground/10 cursor-pointer">
                                    <ExternalLink className="w-3 h-3" /> View
                                  </button>
                                  <button onClick={e => { e.stopPropagation(); exportCardsAsPdf(o) }} disabled={cardsExporting}
                                    className="flex items-center gap-1 px-2 py-1 text-xs rounded border border-border hover:bg-muted-foreground/10 cursor-pointer disabled:opacity-50">
                                    <Download className="w-3 h-3" /> PDF Card
                                  </button>
                                  <button onClick={e => { e.stopPropagation(); setEmailTarget(emailTarget?.offering?.id === o.id ? null : { type: 'card', offering: o }) }}
                                    className="flex items-center gap-1 px-2 py-1 text-xs rounded border border-border hover:bg-muted-foreground/10 cursor-pointer">
                                    <Mail className="w-3 h-3" /> Email Card
                                  </button>
                                </div>
                              </div>
                            </td>
                          </tr>
                        )}
                      </React.Fragment>
                    )
                  })}
                </tbody>
                <tfoot>
                  <tr className="bg-card border-t-2 border-border font-bold">
                    <td className="px-3 py-3">Total</td>
                    <td className="px-3 py-3 text-right">${grandTotal.general.toFixed(2)}</td>
                    <td className="px-3 py-3 text-right">${grandTotal.cash.toFixed(2)}</td>
                    <td className="px-3 py-3 text-right">${grandTotal.sunday_school.toFixed(2)}</td>
                    <td className="px-3 py-3 text-right">${grandTotal.building_fund.toFixed(2)}</td>
                    <td className="px-3 py-3 text-right">${grandTotal.misc.toFixed(2)}</td>
                    <td className="px-3 py-3 text-right text-primary">${grandTotalSum.toFixed(2)}</td>
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>}
        </>
      ) : (
        <div className="rounded-xl border border-border bg-card p-10 text-center">
          <FileText className="w-10 h-10 mx-auto text-muted mb-3" />
          <p className="text-muted">No approved offerings for {periodLabel}</p>
          <p className="text-xs text-muted mt-1">Upload and approve offerings to see them here</p>
        </div>
      )}
    </div>
  )
}
